import {NextRequest,NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {getSession} from '@/lib/platform-auth';
import {FALLBACK_RATES,getCountryCurrency,getCurrencyMeta} from '@/lib/country-currency';
export const dynamic='force-dynamic';
function ipOf(r:NextRequest){return r.headers.get('cf-connecting-ip')?.trim()||r.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||r.headers.get('x-real-ip')?.trim()||'';}
async function detect(r:NextRequest){try{const ip=ipOf(r);const url=ip?'https://ipapi.co/'+encodeURIComponent(ip)+'/json/':'https://ipapi.co/json/';const x=await fetch(url,{cache:'no-store',headers:{accept:'application/json'}});if(!x.ok)return null;const d=await x.json();return {country:String(d.country_code||'').toUpperCase(),currency:String(d.currency||'').toUpperCase()};}catch{return null}}
async function fx(c:string){if(c==='USD')return 1;try{const x=await fetch('https://open.er-api.com/v6/latest/USD',{next:{revalidate:86400}});if(x.ok){const d=await x.json();const n=Number(d?.rates?.[c]);if(Number.isFinite(n)&&n>0)return n;}}catch{}return FALLBACK_RATES[c]||1;}
export async function GET(r:NextRequest){let country='',currency='',source='default';try{const c=await cookies();const s=await getSession(c.get('matos_session')?.value);if(s?.country){country=String(s.country).toUpperCase();currency=getCountryCurrency(country);source='registration';}
    if(!currency){const cookieCountry=r.cookies.get('matos_country')?.value?.trim().toUpperCase()||'';if(/^[A-Z]{2}$/.test(cookieCountry)){country=cookieCountry;currency=getCountryCurrency(country);source='registration-cookie';}}}catch{}if(!currency){const d=await detect(r);country=d?.country||'';currency=d?.currency||getCountryCurrency(country)||'USD';source=d?'ip':'default';}const m=getCurrencyMeta(currency),rate=await fx(currency);return NextResponse.json({country,currency,symbol:m.symbol,name:m.name,rate,options:[{code:currency,symbol:m.symbol,name:m.name,rate},{code:'USD',symbol:'$',name:'US Dollar',rate:1}].filter((x,i,a)=>a.findIndex(y=>y.code===x.code)===i),source});}
