'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useDeriv } from '@/hooks/useDeriv';
import { useLanguage } from '@/contexts/LanguageContext';

type Contract='EVEN'|'ODD'|'OVER'|'UNDER'|'RISE'|'FALL'|'DIFFER'|'MATCH0';
type Strategy='PAR_IMPAR'|'ACIMA5_BAIXO4'|'RISE_FALL'|'DIFERENTE'|'MATCH0';
const MT=64;
const SYMBOLS:Record<string,string>={R_10:'Volatility 10 Index',R_25:'Volatility 25 Index',R_50:'Volatility 50 Index',R_75:'Volatility 75 Index',R_100:'Volatility 100 Index','1HZ10V':'Volatility 10 (1s)','1HZ25V':'Volatility 25 (1s)','1HZ50V':'Volatility 50 (1s)','1HZ75V':'Volatility 75 (1s)','1HZ100V':'Volatility 100 (1s)'};
const TYPES:Record<Contract,string>={EVEN:'DIGITEVEN',ODD:'DIGITODD',OVER:'DIGITOVER',UNDER:'DIGITUNDER',RISE:'CALL',FALL:'PUT',DIFFER:'DIGITDIFF',MATCH0:'DIGITMATCH'};
const decimalPlaces=(pipSize:number)=>{if(!Number.isFinite(pipSize)||pipSize<=0)return 0;return Math.max(0,Math.min(10,Math.round(-Math.log10(pipSize))))};
const digit=(v:number|string|null|undefined,pipSize?:number)=>{if(v==null)return null;let s=String(v).trim();if(pipSize&&Number.isFinite(pipSize)&&pipSize>0&&typeof v==='number'){const places=decimalPlaces(pipSize);s=v.toFixed(places)}const chars=s.match(/\d/g);return chars?.length?Number(chars[chars.length-1]):null};
function stats(v:number[],pipSize?:number){const d=v.map(x=>digit(x,pipSize)).filter((x):x is number=>x!==null),n=d.length||1,even=d.filter(x=>x%2===0).length/n*100,above5=d.filter(x=>x>5).length/n*100,below4=d.filter(x=>x<4).length/n*100,diff=d.filter(x=>x!==0).length/n*100,match0=d.filter(x=>x===0).length/n*100;let up=0,down=0;for(let i=1;i<v.length;i++){if(v[i]>v[i-1])up++;else if(v[i]<v[i-1])down++}const m=Math.max(1,up+down);return{even,odd:100-even,above5,below4,diff,match0,rise:up/m*100,fall:down/m*100,probs:Array.from({length:10},(_,x)=>d.filter(y=>y===x).length/n*100)}}
function makeSignal(v:number[],s:Strategy,pipSize?:number){if(v.length<2)return null;const x=stats(v,pipSize),t=45;if(s==='PAR_IMPAR')return x.even>=t?{contract:'EVEN' as Contract,label:'PAR',strength:x.even}:x.odd>=t?{contract:'ODD' as Contract,label:'ÍMPAR',strength:x.odd}:null;if(s==='ACIMA5_BAIXO4')return x.above5>=t?{contract:'OVER' as Contract,label:'ACIMA 5',strength:x.above5}:x.below4>=t?{contract:'UNDER' as Contract,label:'ABAIXO 4',strength:x.below4}:null;if(s==='RISE_FALL')return x.rise>=t?{contract:'RISE' as Contract,label:'SUBIR',strength:x.rise}:x.fall>=t?{contract:'FALL' as Contract,label:'DESCER',strength:x.fall}:null;if(s==='DIFERENTE')return x.diff>=t?{contract:'DIFFER' as Contract,label:'DIFERENTE DE 0',strength:x.diff}:null;const zeroIsDominant=x.match0>=30&&x.match0>Math.max(...x.probs.slice(1));return zeroIsDominant?{contract:'MATCH0' as Contract,label:'MATCH 0',strength:x.match0}:null}
const money=(u:number,currency:'USD'|'MZN')=>currency==='USD'?`${u>=0?'+':''}${u.toFixed(2)} $`:`${u>=0?'+':''}${(u*MT).toFixed(2)} MT`;
function sound(kind:'win'|'loss'|'target'){try{const C=window.AudioContext||(window as any).webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=kind==='win'?880:kind==='loss'?180:1040;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.35);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.4);setTimeout(()=>c.close(),500)}catch{}}

export default function AutoBotV4(){
 const { t }=useLanguage();
 const[symbol,setSymbol]=useState('1HZ100V'),[account,setAccount]=useState<'demo'|'real'>('demo'),[stake,setStake]=useState(1.5),[strategy,setStrategy]=useState<Strategy>('PAR_IMPAR'),[tickWindow,setTickWindow]=useState(10),[running,setRunning]=useState(false),[ticks,setTicks]=useState<number[]>([]),[tickPipSize,setTickPipSize]=useState<number|undefined>(undefined),[signalNow,setSignalNow]=useState<any>(null),[target,setTarget]=useState(180),[lossLimit,setLossLimit]=useState(35000),[metas,setMetas]=useState(false),[theme,setTheme]=useState<'dark'|'light'>('dark'),[menu,setMenu]=useState(false),[notice,setNotice]=useState<string|null>(null),[currency,setCurrency]=useState<'USD'|'MZN'>('MZN');
 const lastEpoch=useRef<number|null>(null),requested=useRef(false),stopped=useRef(false),lastNotice=useRef<number|null>(null),lastRequestedClose=useRef(0),requestStartedAt=useRef(0),lastActivityAt=useRef(Date.now());
 const{tick,balance,proposal,buy,buying,activeContractId,getProposal,subscribeTicks,isAuthorized,isConnected,error,profitTransactions,soros,setSorosStake,contractClosedSeq,fetchProfitTable}=useDeriv(account);
 const st=useMemo(()=>stats(ticks,tickPipSize),[ticks,tickPipSize]),pnl=useMemo(()=>profitTransactions.reduce((a,x)=>a+Number(x.profit_loss||0),0),[profitTransactions]),latest=profitTransactions[0],closedOperations=Math.min(profitTransactions.length,2000);
 useEffect(()=>{document.body.dataset.theme=theme;return()=>{delete document.body.dataset.theme}},[theme]);
 useEffect(()=>{try{const saved=localStorage.getItem('mozhyper-currency');if(saved==='USD'||saved==='MZN')setCurrency(saved)}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('mozhyper-currency',currency)}catch{}},[currency]);
 useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[isConnected,symbol,subscribeTicks]);
 useEffect(()=>{if(!tick?.epoch||tick.epoch===lastEpoch.current)return;lastEpoch.current=tick.epoch;lastActivityAt.current=Date.now();const q=Number(tick.quote);if(!Number.isFinite(q))return;if(Number.isFinite((tick as any).pip_size)&&Number((tick as any).pip_size)>0)setTickPipSize(Number((tick as any).pip_size));const pipSize=Number((tick as any).pip_size)>0?Number((tick as any).pip_size):tickPipSize;setTicks(prev=>{const n=[...prev,q];if(n.length>=tickWindow){setSignalNow(makeSignal(n.slice(-tickWindow),strategy,pipSize));return[]}return n})},[tick,strategy,tickWindow,tickPipSize]);
 useEffect(()=>{setSorosStake(stake)},[stake,setSorosStake]);
 useEffect(()=>{setTicks([]);setSignalNow(null);setTickPipSize(undefined);requested.current=false;requestStartedAt.current=0;lastActivityAt.current=Date.now()},[tickWindow,strategy,symbol]);
 useEffect(()=>{if(!running||!isConnected)return;const id=window.setInterval(()=>fetchProfitTable({limit:500,offset:0,sort:'DESC'}),5000);return()=>window.clearInterval(id)},[running,isConnected,fetchProfitTable]);
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>{if(requested.current&&requestStartedAt.current>0&&!proposal&&!buying&&activeContractId===null&&Date.now()-requestStartedAt.current>1800){requested.current=false;requestStartedAt.current=0}if(signalNow&&!proposal&&!buying&&activeContractId===null&&Date.now()-lastActivityAt.current>5500){requested.current=false;requestStartedAt.current=0;subscribeTicks(symbol);lastActivityAt.current=Date.now()-4500}},1000);return()=>window.clearInterval(id)},[running,proposal,buying,activeContractId,signalNow,symbol,subscribeTicks]);
 useEffect(()=>{if(!running||stopped.current||!signalNow||proposal||buying||!isAuthorized||!isConnected)return;const closeChanged=contractClosedSeq!==lastRequestedClose.current;if(closeChanged&&activeContractId===null){requested.current=false;requestStartedAt.current=0;lastRequestedClose.current=contractClosedSeq;lastActivityAt.current=Date.now()}if(requested.current||activeContractId!==null)return;requested.current=true;requestStartedAt.current=Date.now();lastActivityAt.current=Date.now();const c:Contract=signalNow.contract as Contract;const barrier=c==='DIFFER'?0:c==='MATCH0'?0:c==='OVER'?5:c==='UNDER'?4:0;const amount=Number(soros.stake)>0?soros.stake:stake;if(!getProposal(symbol,TYPES[c],amount,1,barrier)){requested.current=false;requestStartedAt.current=0}},[running,signalNow,proposal,buying,activeContractId,isAuthorized,isConnected,getProposal,symbol,soros.stake,stake,contractClosedSeq]);
 useEffect(()=>{if(running&&proposal&&!buying&&activeContractId===null){requested.current=false;requestStartedAt.current=0;lastActivityAt.current=Date.now();buy(proposal.id,proposal.ask_price)}},[running,proposal,buying,activeContractId,buy]);
 useEffect(()=>{if(!running||stopped.current)return;const p=pnl*MT;if(p>=target){stopped.current=true;requested.current=false;requestStartedAt.current=0;setRunning(false);setNotice(`🎯 ${t('goalReached')}: ${money(pnl,currency)}`);sound('target')}else if(p<=-lossLimit){stopped.current=true;requested.current=false;requestStartedAt.current=0;setRunning(false);setNotice(`🛑 ${t('lossGoal')}: ${money(pnl,currency)}`);sound('loss')}},[pnl,target,lossLimit,running,t,currency]);
 useEffect(()=>{const id=latest?.contract_id;if(!id||id===lastNotice.current||!latest?.sell_time)return;lastNotice.current=id;const profit=Number(latest.profit_loss||0),win=profit>=0;setNotice(`${win?'✅ WIN':'❌ LOSS'} · ${money(profit,currency)}`);sound(win?'win':'loss');lastActivityAt.current=Date.now()},[latest,currency]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),4000);return()=>clearTimeout(timer)},[notice]);
 const start=()=>{if(!isConnected||!isAuthorized)return;stopped.current=false;requested.current=false;requestStartedAt.current=0;lastRequestedClose.current=contractClosedSeq;lastActivityAt.current=Date.now();setTicks([]);setSignalNow(null);setRunning(true)};
 const stop=()=>{stopped.current=true;requested.current=false;requestStartedAt.current=0;setRunning(false);setSignalNow(null)};
 return <div className="min-h-screen w-full bg-slate-950 text-white">{/* existing UI */}</div>;
}
