'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useDeriv } from '@/hooks/useDeriv';

type Contract = 'EVEN' | 'ODD' | 'OVER' | 'UNDER' | 'RISE' | 'FALL';
type Strategy = 'PAR_IMPAR' | 'ACIMA_ABAIXO' | 'RISE_FALL';
const MT = 68;
const SYMBOLS: Record<string,string> = { R_10:'Volatility 10 Index',R_25:'Volatility 25 Index',R_50:'Volatility 50 Index',R_75:'Volatility 75 Index',R_100:'Volatility 100 Index','1HZ10V':'Volatility 10 (1s)','1HZ25V':'Volatility 25 (1s)','1HZ50V':'Volatility 50 (1s)','1HZ75V':'Volatility 75 (1s)','1HZ100V':'Volatility 100 (1s)' };
const TYPES: Record<Contract,string> = { EVEN:'DIGITEVEN',ODD:'DIGITODD',OVER:'DIGITOVER',UNDER:'DIGITUNDER',RISE:'CALL',FALL:'PUT' };
function digit(v:number|string|null|undefined){if(v==null)return null;const s=String(v).replace(/\D/g,'');return s?Number(s.slice(-1)):null;}
function stats(v:number[]){const d=v.map(digit).filter((x):x is number=>x!==null),n=d.length||1;const even=d.filter(x=>x%2===0).length/n*100;const over=d.filter(x=>x>4).length/n*100;let up=0,down=0;for(let i=1;i<v.length;i++){if(v[i]>v[i-1])up++;else if(v[i]<v[i-1])down++;}const moves=Math.max(1,up+down);return{even,odd:100-even,over,under:100-over,rise:up/moves*100,fall:down/moves*100,probs:Array.from({length:10},(_,x)=>d.filter(y=>y===x).length/n*100)};}
function signal(v:number[],strategy:Strategy){if(v.length<2)return null;const s=stats(v),t=60;if(strategy==='PAR_IMPAR'){if(s.even>=t)return{contract:'EVEN' as Contract,label:'PAR',strength:s.even};if(s.odd>=t)return{contract:'ODD' as Contract,label:'ÍMPAR',strength:s.odd};}if(strategy==='ACIMA_ABAIXO'){if(s.over>=t)return{contract:'OVER' as Contract,label:'ACIMA 4',strength:s.over};if(s.under>=t)return{contract:'UNDER' as Contract,label:'ABAIXO 5',strength:s.under};}if(strategy==='RISE_FALL'){if(s.rise>=t)return{contract:'RISE' as Contract,label:'SUBIR',strength:s.rise};if(s.fall>=t)return{contract:'FALL' as Contract,label:'DESCER',strength:s.fall};}return null;}
const money=(u:number)=>`${u>=0?'+':''}${(u*MT).toFixed(2)} MT`;
function sound(kind:'win'|'loss'|'target'){try{const C=window.AudioContext||(window as any).webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();const f=kind==='win'?[660,880,1040]:kind==='loss'?[240,180,120]:[520,760,1040];o.type='sine';o.frequency.value=f[0];f.slice(1).forEach((x,i)=>o.frequency.setValueAtTime(x,c.currentTime+(i+1)*.12));g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.16,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.48);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.5);setTimeout(()=>c.close(),700);}catch{}}

export default function AutoBotV3(){
 const[symbol,setSymbol]=useState('1HZ100V'),[account,setAccount]=useState<'demo'|'real'>('demo'),[stake,setStake]=useState(1.5),[strategy,setStrategy]=useState<Strategy>('PAR_IMPAR'),[running,setRunning]=useState(false),[ticks,setTicks]=useState<number[]>([]),[signalNow,setSignalNow]=useState<any>(null),[target,setTarget]=useState(680),[lossLimit,setLossLimit]=useState(680),[metas,setMetas]=useState(false),[menu,setMenu]=useState(false),[theme,setTheme]=useState<'dark'|'light'>('dark'),[notice,setNotice]=useState<string|null>(null);
 const lastEpoch=useRef<number|null>(null),requested=useRef(false),stopped=useRef(false),lastNotice=useRef<number|null>(null);
 const{tick,balance,proposal,buy,buying,activeContractId,getProposal,subscribeTicks,isAuthorized,isConnected,error,profitTransactions,soros,resetSoros,setSorosEnabled,setSorosStake}=useDeriv(account);
 const st=useMemo(()=>stats(ticks),[ticks]);const pnl=useMemo(()=>profitTransactions.reduce((s,x)=>s+Number(x.profit_loss||0),0),[profitTransactions]);const latest=profitTransactions[0];
 useEffect(()=>{document.body.dataset.theme=theme;return()=>{delete document.body.dataset.theme}},[theme]);
 useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[isConnected,symbol,subscribeTicks]);
 useEffect(()=>{if(!tick?.epoch||tick.epoch===lastEpoch.current)return;lastEpoch.current=tick.epoch;const q=Number(tick.quote);if(!Number.isFinite(q))return;setTicks(p=>{const n=[...p,q];if(n.length>=10){setSignalNow(signal(n.slice(-10),strategy));return[];}return n;})},[tick,strategy]);
 useEffect(()=>{if(stake>=1.5)setSorosStake(stake)},[stake,setSorosStake]);
 useEffect(()=>{if(!running||stopped.current||!signalNow||requested.current||proposal||buying||activeContractId!==null||!isAuthorized||!isConnected)return;requested.current=true;const b=signalNow.contract==='OVER'?4:signalNow.contract==='UNDER'?5:0;if(!getProposal(symbol,TYPES[signalNow.contract],stake,1,b))requested.current=false;},[running,signalNow,proposal,buying,activeContractId,isAuthorized,isConnected,getProposal,symbol,stake]);
 useEffect(()=>{if(running&&proposal&&!buying&&activeContractId===null)buy(proposal.id,proposal.ask_price)},[running,proposal,buying,activeContractId,buy]);
 useEffect(()=>{if(activeContractId===null&&!buying&&!proposal)requested.current=false},[activeContractId,buying,proposal]);
 useEffect(()=>{if(!running||stopped.current)return;if(pnl*MT>=target){stopped.current=true;requested.current=false;setRunning(false);setNotice(`Meta de lucro atingida: ${money(pnl)}`);sound('target');}else if(pnl*MT<=-lossLimit){stopped.current=true;requested.current=false;setRunning(false);setNotice(`Meta de perdas atingida: ${money(pnl)}`);sound('loss');}},[pnl,target,lossLimit,running]);
 useEffect(()=>{const id=latest?.contract_id;if(!id||id===lastNotice.current||!latest?.sell_time)return;lastNotice.current=id;const win=Number(latest.profit_loss||0)>=0;setNotice(`${win?'WIN':'LOSS'} · ${money(Number(latest.profit_loss||0))}`);sound(win?'win':'loss');},[latest]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(null),3500);return()=>clearTimeout(t)},[notice]);
 const start=()=>{if(!isConnected||!isAuthorized)return;stopped.current=false;requested.current=false;setTicks([]);setSignalNow(null);setRunning(true);};const stop=()=>{stopped.current=true;requested.current=false;setRunning(false);setSignalNow(null);};
 return <div className="mx-auto flex min-h-full w-full max-w-[430px] flex-col gap-3 bg-slate-950 p-4 text-slate-100"><style>{`body[data-theme=light]{background:#f4f7fb!important}.mh-head{display:flex;align-items:center;justify-content:space-between}.mh-actions{display:flex;gap:6px}.mh-btn{border:1px solid #334155;background:#111827;color:#e2e8f0;border-radius:9px;height:34px;padding:0 10px;font-weight:800}.mh-menu{position:absolute;right:16px;top:50px;z-index:80;background:#111827;border:1px solid #334155;border-radius:12px;padding:6px;width:150px;box-shadow:0 18px 40px #0008}.mh-menu button{display:block;width:100%;border:0;background:transparent;color:#e2e8f0;text-align:left;padding:9px;border-radius:8px;font-size:11px}.hist{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none}.trade{min-width:105px;border:1px solid #334155;border-radius:10px;background:#0f172a;padding:9px}.candle{height:30px;width:8px;margin:0 auto 5px;position:relative}.candle:before{content:'';position:absolute;left:3px;top:0;width:1px;height:30px;background:currentColor}.candle:after{content:'';position:absolute;left:1px;top:8px;width:5px;height:13px;background:currentColor}.blue{color:#3b82f6}.red{color:#ef4444}`}</style>
 <div className="mh-head relative"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-600 font-black shadow-lg">M</div><div><b>Moz<span className="text-blue-500">Hyper</span></b><div className="text-[8px] uppercase text-slate-500">Automático</div></div></div><div className="mh-actions"><button className="mh-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀':'☾'}</button><button className="mh-btn" onClick={()=>setMenu(!menu)}>⋯</button></div>{menu&&<div className="mh-menu"><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Modo light':'Modo dark'}</button><button onClick={()=>setMetas(true)}>Metas</button><button onClick={()=>{stop();location.href='/'}}>Sair</button></div>}</div>
 {notice&&<div className="fixed left-1/2 top-4 z-[200] w-[calc(100%-28px)] max-w-[390px] -translate-x-1/2 rounded-xl border border-blue-500 bg-slate-900 p-3 text-center text-sm font-bold shadow-2xl">{notice}</div>}
 {metas&&<div className="fixed inset-0 z-[190] flex items-center justify-center bg-black/70 p-5"><div className="w-full max-w-[350px] rounded-2xl border border-slate-700 bg-slate-900 p-5"><div className="flex justify-between"><b>Metas</b><button onClick={()=>setMetas(false)}>✕</button></div><label className="mt-5 block text-xs text-slate-400">Meta de lucros<input className="mt-2 w-full rounded-lg bg-slate-950 p-3 font-bold" type="number" min="1" value={target} onChange={e=>setTarget(Math.max(1,Number(e.target.value)||1))}/><small> MT</small></label><label className="mt-4 block text-xs text-slate-400">Meta de perdas<input className="mt-2 w-full rounded-lg bg-slate-950 p-3 font-bold" type="number" min="1" value={lossLimit} onChange={e=>setLossLimit(Math.max(1,Number(e.target.value)||1))}/><small> MT</small></label><button className="mt-5 w-full rounded-lg bg-blue-600 p-3 font-bold" onClick={()=>setMetas(false)}>Guardar</button></div></div>}
 <div className="rounded-xl border border-emerald-800 bg-slate-900 p-4"><div className="flex justify-between"><div><b className="text-xs">Soros · 3 passos</b><div className="text-[9px] text-slate-400">Fase {soros.level+1} · Entrada US$ {(soros.enabled?soros.stake:stake).toFixed(2)}</div></div><button className="rounded-lg border border-emerald-700 px-3 py-2 text-[9px]" disabled={running} onClick={()=>{setSorosEnabled(!soros.enabled);if(!soros.enabled)resetSoros()}}>{soros.enabled?'ATIVO':'DESLIGADO'}</button></div></div>
 <div className="grid grid-cols-2 rounded-xl border border-slate-700 bg-slate-900"><div className="p-4"><div className="text-[9px] text-slate-500">Saldo</div><b>{balance?`${Number(balance.balance).toFixed(2)} ${balance.currency}`:'—'}</b></div><div className="border-l border-slate-700 p-4"><div className="text-[9px] text-slate-500">Lucro/Perda</div><b className={pnl>=0?'text-emerald-400':'text-red-400'}>{money(pnl)}</b></div></div>
 <div className="grid grid-cols-2 gap-2"><label className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-xs">Conta<select className="mt-1 w-full bg-transparent font-bold" value={account} onChange={e=>setAccount(e.target.value as 'demo'|'real')} disabled={running}><option value="demo">Demo</option><option value="real">Real</option></select></label><label className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-xs">Estratégia<select className="mt-1 w-full bg-transparent font-bold" value={strategy} onChange={e=>setStrategy(e.target.value as Strategy)} disabled={running}><option value="PAR_IMPAR">Par / Ímpar</option><option value="ACIMA_ABAIXO">Acima / Abaixo</option><option value="RISE_FALL">Subir / Descer</option></select></label></div>
 <div className="rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="text-[9px] uppercase text-slate-500">Estado do robô · 10 ticks</div><div className="mt-2 flex items-center justify-between"><b className={running?'text-emerald-400':''}>{running?'Em execução':'Parado'}</b><span className="font-mono">{tick?.quote??'—'}</span></div><div className="mt-4 grid grid-cols-10 items-end gap-1">{st.probs.map((p,i)=><div key={i} className="text-center"><div className={`mx-auto w-2 rounded-sm ${p>=10?'bg-blue-500':'bg-red-500'}`} style={{height:`${Math.max(7,Math.min(50,p/2))}px`}}/><div className="text-[7px] text-slate-500">{i}</div><div className="text-[7px] text-slate-500">{p.toFixed(0)}%</div></div>)}</div></div>
 <div className="rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="text-[9px] uppercase text-slate-500">Gestão de risco · Stake</div><div className="mt-3 flex items-center justify-between"><button className="h-9 w-9 rounded-lg bg-slate-950" disabled={running} onClick={()=>setStake(x=>Math.max(1.5,Number((x-.1).toFixed(2))))}>−</button><b className="font-mono text-xl">${stake.toFixed(2)}</b><button className="h-9 w-9 rounded-lg bg-slate-950" disabled={running} onClick={()=>setStake(x=>Number((x+.1).toFixed(2)))}>+</button></div><div className="mt-2 text-[8px] text-slate-500">Este Stake é a entrada inicial do Soros.</div></div>
 <div className="rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="flex justify-between"><b className="text-[9px] uppercase text-slate-500">Histórico de trades recentes</b><span className="text-[8px] text-slate-500">deslize →</span></div><div className="hist mt-3">{profitTransactions.slice(0,12).map(x=>{const p=Number(x.profit_loss||0);return <div className="trade" key={x.contract_id}><div className={`candle ${p>=0?'blue':'red'}`}/><b className={`text-[10px] ${p>=0?'text-emerald-400':'text-red-400'}`}>{p>=0?'WIN':'LOSS'}</b><div className="text-[8px] text-slate-400">{x.contract_type||'Trade'}</div><div className="font-mono text-[10px]">{p>=0?'+':''}{p.toFixed(2)}</div><div className="text-[7px] text-slate-500">Tick {x.exit_tick??'—'}</div></div>;})}{!profitTransactions.length&&<div className="p-4 text-[9px] text-slate-500">Nenhum trade fechado.</div>}</div></div>
 <div className="grid grid-cols-2 gap-2"><label className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-xs">Símbolo<select className="mt-1 w-full bg-transparent font-bold" value={symbol} onChange={e=>setSymbol(e.target.value)} disabled={running}>{Object.entries(SYMBOLS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-xs"><div className="text-[9px] text-slate-500">Meta</div><div className="mt-1 font-bold">{money(pnl)} / {target} MT</div><button className="mt-2 text-[9px] text-blue-400" onClick={()=>setMetas(true)}>Abrir Metas</button></div></div>
 {error&&<div className="rounded-xl border border-red-800 bg-red-950 p-3 text-xs text-red-300">{error}</div>}
 <button className={`w-full rounded-xl p-4 font-bold ${running?'bg-red-600':'bg-blue-600'}`} disabled={!isConnected||!isAuthorized} onClick={running?stop:start}>{running?'■ PARAR ROBÔ':'▶ INICIAR ROBÔ'}</button>
 <div className="flex justify-between text-[9px] text-slate-500"><span>{SYMBOLS[symbol]}</span><span>{isConnected&&isAuthorized?'● Conectado':'○ A ligar…'}</span></div>
 </div>
}
