'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useDeriv} from '@/hooks/useDeriv';
type Contract='EVEN'|'ODD'|'OVER'|'UNDER';
const CT:Record<Contract,string>={EVEN:'DIGITEVEN',ODD:'DIGITODD',OVER:'DIGITOVER',UNDER:'DIGITUNDER'};
const SYMBOLS:Record<string,string>={R_10:'Volatility 10 Index',R_25:'Volatility 25 Index',R_50:'Volatility 50 Index',R_75:'Volatility 75 Index',R_100:'Volatility 100 Index','1HZ10V':'Volatility 10 (1s) Index','1HZ25V':'Volatility 25 (1s) Index','1HZ50V':'Volatility 50 (1s) Index','1HZ75V':'Volatility 75 (1s) Index','1HZ100V':'Volatility 100 (1s) Index'};
const SYMBOL_OPTIONS=Object.keys(SYMBOLS),USD_TO_MZN=68;const PH={INITIAL:1,SOROS:1.95,MG1:2,MG2:4.1,MG3:8.4} as const;type Phase=keyof typeof PH|'STOP';type Signal={contract:Contract;pct:number;reason:string};
function digit(v:any){if(v==null)return null;const s=String(v).replace(/\D/g,'');return s?Number(s.slice(-1)):null}function pct(a:number[],f:(d:number)=>boolean){const x=a.map(digit).filter((d):d is number=>d!==null);return x.length?x.filter(f).length/x.length*100:0}function signal(a:number[]):Signal|null{if(a.length<10)return null;const x=a.slice(-10),e=pct(x,d=>d%2===0),o=pct(x,d=>d>4);if(e>=60)return{contract:'EVEN',pct:Math.round(e),reason:`PAR ${Math.round(e)}%`};if(100-e>=60)return{contract:'ODD',pct:Math.round(100-e),reason:`ÍMPAR ${Math.round(100-e)}%`};if(o>=60)return{contract:'OVER',pct:Math.round(o),reason:`ACIMA 4 ${Math.round(o)}%`};if(100-o>=60)return{contract:'UNDER',pct:Math.round(100-o),reason:`ABAIXO 5 ${Math.round(100-o)}%`};return null}
function DigitMini({ticks}:{ticks:number[]}){const d=Array.from({length:10},(_,i)=>ticks.length?Math.round(pct(ticks.slice(-10),x=>x===i)):0);return <div className="card"><div className="label">ANÁLISE LIVE <span>{ticks.length}/10 TICKS</span></div><div className="digits">{d.map((p,i)=><div key={i}><b>{i}</b><i style={{height:Math.max(4,Math.min(30,p*.3))}}/><small>{p}%</small></div>)}</div></div>}
function BotWorker(p:{symbol:string;accountType:'demo'|'real';target:number;stop:number;stake:number;onSymbol:(s:string)=>void}){const{symbol,accountType,target,stop,stake:baseStake,onSymbol}=p;const{balance,tick,proposal,buy,buying,activeContractId,getProposal,subscribeTicks,isAuthorized,isConnected,profitTransactions,contractClosedSeq}=useDeriv(accountType);const[running,setRunning]=useState(false),[ticks,setTicks]=useState<number[]>([]),[sig,setSig]=useState<Signal|null>(null),[phase,setPhase]=useState<Phase>('INITIAL'),[started,setStarted]=useState<number|null>(null),[losses,setLosses]=useState(0),[closed,setClosed]=useState(0);const epoch=useRef<number|null>(null),tradeEpoch=useRef<number|null>(null),requested=useRef(false),lastContract=useRef<number|null>(null);
useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[isConnected,symbol,subscribeTicks]);useEffect(()=>{if(!tick?.epoch||tick.epoch===epoch.current)return;epoch.current=tick.epoch;setTicks(v=>[...v.slice(-9),Number(tick.quote)])},[tick]);useEffect(()=>setSig(signal(ticks)),[ticks]);
const session=useMemo(()=>started?profitTransactions.filter(x=>Number(x.purchase_time)>=started):[],[profitTransactions,started]);const profit=session.reduce((s,x)=>s+Number(x.profit_loss||0),0),wins=session.filter(x=>Number(x.profit_loss||0)>=0).length,rate=session.length?Math.round(wins/session.length*100):0;const mult=phase==='INITIAL'||phase==='STOP'?1:PH[phase],currentStake=baseStake*mult;
useEffect(()=>{if(!started||contractClosedSeq===closed)return;setClosed(contractClosedSeq);requested.current=false},[contractClosedSeq,started,closed]);useEffect(()=>{const x=profitTransactions[0];if(!x?.contract_id||x.contract_id===lastContract.current||!started||Number(x.purchase_time)<started)return;lastContract.current=x.contract_id;const v=Number(x.profit_loss||0);if(v>=0){setLosses(0);setPhase(q=>q==='INITIAL'?'SOROS':'INITIAL')}else{const n=losses+1;setLosses(n);if(phase==='INITIAL'||phase==='SOROS')setPhase('MG1');else if(phase==='MG1')setPhase('MG2');else if(phase==='MG2')setPhase('MG3');else{setPhase('STOP');setRunning(false)}}},[profitTransactions,started,phase,losses]);
useEffect(()=>{if(running&&profit>=target/USD_TO_MZN){setRunning(false)}if(running&&profit<=-stop/USD_TO_MZN){setRunning(false);setPhase('STOP')}},[running,profit,target,stop]);useEffect(()=>{if(!running||!isAuthorized||!isConnected||buying||proposal||activeContractId!==null||!sig||requested.current)return;const e=Number(tick?.epoch);if(!e||(tradeEpoch.current!==null&&e<=tradeEpoch.current))return;requested.current=true;tradeEpoch.current=e;const ok=getProposal(symbol,CT[sig.contract],currentStake,1,sig.contract==='OVER'?4:sig.contract==='UNDER'?5:0);if(!ok)requested.current=false},[running,isAuthorized,isConnected,buying,proposal,activeContractId,sig,symbol,getProposal,currentStake,tick?.epoch]);useEffect(()=>{if(running&&proposal&&!buying&&activeContractId===null){buy(proposal.id,proposal.ask_price)}},[proposal,running,buying,activeContractId,buy]);
const start=()=>{if(!isAuthorized||!isConnected)return;setStarted(Math.floor(Date.now()/1000));setTicks([]);setSig(null);setLosses(0);setPhase('INITIAL');setRunning(true);requested.current=false;tradeEpoch.current=null;lastContract.current=null};const phaseLabel=phase==='STOP'?'STOP':phase==='INITIAL'?`Inicial $${baseStake.toFixed(2)}`:phase==='SOROS'?`Soros $${currentStake.toFixed(2)}`:`MG ${phase.replace('MG','')} $${currentStake.toFixed(2)}`;const name=sig?(sig.contract==='EVEN'?'PAR':sig.contract==='ODD'?'ÍMPAR':sig.contract==='OVER'?'ACIMA 4':'ABAIXO 5'):'Aguardando';return <div className="worker">
<div className="finance"><div><small>SALDO</small><b>{balance?`${Number(balance.balance).toFixed(2)} ${balance.currency}`:'—'}</b></div><div><small>RESULTADO HOJE</small><b className={profit>=0?'up':'down'}>{profit>=0?'+':''}{(profit*USD_TO_MZN).toFixed(0)} MT</b></div><button className={running?'live':''} onClick={running?()=>setRunning(false):start}>{running?'● LIVE':'▶ INICIAR'}</button></div>
<div className="card"><div className="label">🎯 METAS <span>EDITÁVEIS NO PAINEL</span></div><div className="goalview"><div><small>Meta diária</small><b>{target.toFixed(0)} MT</b></div><div><small>Stop Loss</small><b>{stop.toFixed(0)} MT</b></div></div></div>
<div className="card"><div className="label">RESULTADOS <span>{rate}% WIN RATE</span></div><div className="stats"><div><b>{wins}</b><small>WINS</small></div><div><b>{session.length-wins}</b><small>LOSS</small></div><div><b>{ticks.length}/10</b><small>TICKS</small></div><div><b>{losses}</b><small>SEQ.</small></div></div></div>
<div className="card"><div className="label">PROFIT TABLE <span>AO VIVO</span></div>{profitTransactions.slice(0,6).map((x:any)=><div className="row" key={x.contract_id}><span>{new Date(Number(x.sell_time||x.purchase_time)*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><b>{Number(x.profit_loss)>=0?'WIN':'LOSS'}</b><strong className={Number(x.profit_loss)>=0?'up':'down'}>{Number(x.profit_loss)>=0?'+':''}{(Number(x.profit_loss)*USD_TO_MZN).toFixed(0)} MT</strong></div>)}{!profitTransactions.length&&<div className="empty">Sem operações ainda</div>}</div>
<div className="card"><div className="label">ROBÔ <span>{isConnected?'● DERIV LIVE':'A LIGAR'}</span></div><div className="botline"><strong>{name}</strong><em>{sig?.reason||'Aguardando 10 ticks'}</em></div><div className="meta"><span>Fase <b>{phaseLabel}</b></span><span>Stake <b>${currentStake.toFixed(2)}</b></span></div></div><DigitMini ticks={ticks}/>
<div className="card controls"><label>Índice<select value={symbol} onChange={e=>{setRunning(false);requested.current=false;setTicks([]);setSig(null);onSymbol(e.target.value)}}>{SYMBOL_OPTIONS.map(s=><option key={s} value={s}>{SYMBOLS[s]}</option>)}</select></label><label>Stake<b>${baseStake.toFixed(2)}</b></label></div></div>}

export default function AutoBot(){const[symbol,setSymbol]=useState('1HZ100V'),[target,setTarget]=useState(3400),[stop,setStop]=useState(2040),[stake,setStake]=useState(1),[accountType,setAccountType]=useState<'demo'|'real'>('demo');return <div className="auto-bot"><style jsx global>{`.auto-bot{padding:10px;background:var(--bg);color:var(--t1);font-family:Inter,system-ui}.worker{max-width:520px;margin:auto}.card,.finance{background:var(--s1);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:11px;margin-bottom:8px}.finance{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:center}.finance small,.label,.controls label{display:block;color:var(--t3);font-size:9px;font-weight:800;letter-spacing:.05em}.finance b{display:block;font-size:17px;margin-top:4px}.finance button{border:0;border-radius:9px;padding:9px;background:var(--s3);color:var(--t1);font-size:9px;font-weight:900}.finance button.live{color:#2fd480}.label span{float:right}.goalview{display:grid;grid-template-columns:1fr 1fr;gap:8px}.goalview div{background:var(--s2);padding:9px;border-radius:9px}.goalview small{display:block;color:var(--t3);font-size:8px}.goalview b{font-size:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.stats div{background:var(--s2);padding:8px 3px;text-align:center;border-radius:9px}.stats b{display:block;font-size:15px}.stats small{font-size:7px;color:var(--t3)}.row{display:grid;grid-template-columns:.8fr 1fr 1fr;padding:8px 2px;border-top:1px solid rgba(255,255,255,.06);font-size:10px}.row b{text-align:center;font-size:9px}.row strong{text-align:right}.botline{display:flex;justify-content:space-between;align-items:center}.botline strong{font-size:16px}.botline em{font-style:normal;color:var(--t3);font-size:9px}.meta{display:flex;justify-content:space-between;margin-top:8px;color:var(--t3);font-size:9px}.meta b{color:var(--t1)}.digits{display:grid;grid-template-columns:repeat(10,1fr);gap:4px}.digits div{background:var(--s2);border-radius:7px;text-align:center;padding:5px 1px}.digits b,.digits small{display:block;font-size:8px}.digits i{display:block;width:5px;margin:3px auto;background:#3b82f6;border-radius:3px}.controls{display:grid;grid-template-columns:1fr 1fr;gap:8px}.controls select{display:block;width:100%;margin-top:5px;background:var(--s2);border:0;border-radius:8px;padding:9px;color:var(--t1);font-size:9px}.controls label>b{display:block;margin-top:8px;font-size:12px}.up{color:#2fd480!important}.down{color:#f0495a!important}.empty{text-align:center;color:var(--t3);font-size:9px;padding:8px}
`}</style><div className="card"><div className="label">CONFIGURAÇÃO <span>{accountType==='real'?'CONTA REAL':'CONTA DEMO'}</span></div><div className="controls"><label>Meta diária<input type="number" value={target} onChange={e=>setTarget(Math.max(0,Number(e.target.value)||0))}/></label><label>Stop Loss<input type="number" value={stop} onChange={e=>setStop(Math.max(0,Number(e.target.value)||0))}/></label></div><div className="account"><button className={accountType==='demo'?'selected':''} onClick={()=>setAccountType('demo')}>Demo</button><button className={accountType==='real'?'selected':''} onClick={()=>setAccountType('real')}>Real</button></div></div><BotWorker symbol={symbol} accountType={accountType} target={target} stop={stop} stake={stake} onSymbol={setSymbol}/></div>}
