'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useDeriv } from '@/hooks/useDeriv';
import { useLanguage } from '@/contexts/LanguageContext';

const CONTRACT_TYPES = { OVER:'DIGITOVER', UNDER:'DIGITUNDER', MATCH:'DIGITMATCH', DIFFERS:'DIGITDIFF', EVEN:'DIGITEVEN', ODD:'DIGITODD' } as const;
type ContractChoice = keyof typeof CONTRACT_TYPES;
const SYMBOLS: Record<string,string> = { R_100:'Volatility 100 Index', R_50:'Volatility 50 Index', R_10:'Volatility 10 Index', R_25:'Volatility 25 Index', R_75:'Volatility 75 Index', '1HZ100V':'Volatility 100 (1s) Index', '1HZ50V':'Volatility 50 (1s) Index' };
const PROBS=[10,10,10,10,10,10,10,10,10,10];
const MIN_STAKE=1.50;
const USD_TO_MZN=68;
type Theme='dark'|'light';
type AudioWindow=Window & {webkitAudioContext?:typeof AudioContext};
let audioCtx:AudioContext|null=null;
let audioUnlocked=false;

function unlockAudio(){if(typeof window==='undefined')return;try{const AC=window.AudioContext||(window as AudioWindow).webkitAudioContext;if(!AC)return;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')void audioCtx.resume();audioUnlocked=true}catch{}}
function playSound(kind:'tick'|'buy'|'win'|'loss'|'goal'){if(typeof window==='undefined')return;try{unlockAudio();if(!audioCtx||!audioUnlocked)return;const notes=kind==='win'?[523.25,659.25,783.99,1046.5]:kind==='goal'?[659.25,783.99,1046.5,1318.51]:kind==='loss'?[440,349.23,261.63]:kind==='buy'?[520,760]:[620];const now=audioCtx.currentTime;const step=kind==='win'||kind==='goal'?.075:.08;notes.forEach((freq,i)=>{const osc=audioCtx!.createOscillator();const gain=audioCtx!.createGain();osc.type=kind==='loss'?'sawtooth':'sine';osc.frequency.setValueAtTime(freq,now+i*step);gain.gain.setValueAtTime(.0001,now+i*step);gain.gain.exponentialRampToValueAtTime(kind==='tick'?.05:.11,now+i*step+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+i*step+.16);osc.connect(gain);gain.connect(audioCtx!.destination);osc.start(now+i*step);osc.stop(now+i*step+.18);});}catch{}}

export default function DigitsGameV3(){
 const {t,language,setLanguage}=useLanguage();
 const {balance,tick,proposal,buying,getProposal,buy,subscribeTicks,isAuthorized,isConnected,error,profitTransactions}=useDeriv();
 const [contractType,setContractType]=useState<ContractChoice>('MATCH');
 const [amount,setAmount]=useState(MIN_STAKE);const [amountText,setAmountText]=useState('1.50');
 const [symbol,setSymbol]=useState('R_100');const [symbolOpen,setSymbolOpen]=useState(false);const [digit,setDigit]=useState(5);const [predictionOpen,setPredictionOpen]=useState(false);const [menuOpen,setMenuOpen]=useState(false);
 const [duration,setDuration]=useState(1);const [countdown,setCountdown]=useState(1);const [tradeActive,setTradeActive]=useState(false);
 const [theme,setTheme]=useState<Theme>(()=>typeof window!=='undefined'&&localStorage.getItem('mozhyper-theme')==='light'?'light':'dark');
 const [result,setResult]=useState<{id:number;pnl:number;exitSpot:string;finalDigit:string;chosenDigit:number;contractType:ContractChoice}|null>(null);
 const [goalPopup,setGoalPopup]=useState<{id:number;target:number;kind:'gain'|'loss'}|null>(null);
 const [goalsOpen,setGoalsOpen]=useState(false);const [gainGoalText,setGainGoalText]=useState('');const [lossGoalText,setLossGoalText]=useState('');const [gainGoal,setGainGoal]=useState<number|null>(null);const [lossGoal,setLossGoal]=useState<number|null>(null);const [goalNotified,setGoalNotified]=useState(false);
 const lastTick=useRef<number|null>(null);const lastClosed=useRef<number|null>(null);const ticksElapsed=useRef(0);const tradeStartedAt=useRef<number|null>(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('mozhyper-theme',theme)},[theme]);
 useEffect(()=>{const activate=()=>unlockAudio();window.addEventListener('pointerdown',activate,{passive:true});window.addEventListener('touchstart',activate,{passive:true});window.addEventListener('keydown',activate,{passive:true});return()=>{window.removeEventListener('pointerdown',activate);window.removeEventListener('touchstart',activate);window.removeEventListener('keydown',activate)}},[]);
 useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[symbol,isConnected,subscribeTicks]);
 useEffect(()=>{if(isAuthorized&&isConnected&&!tradeActive)getProposal(symbol,CONTRACT_TYPES[contractType],Math.max(MIN_STAKE,amount),duration,digit)},[contractType,amount,digit,symbol,duration,isAuthorized,isConnected,tradeActive,getProposal]);
 useEffect(()=>{if(!tradeActive||!tick?.epoch||lastTick.current===tick.epoch)return;lastTick.current=tick.epoch;ticksElapsed.current=Math.min(duration,ticksElapsed.current+1);playSound('tick');setCountdown(Math.max(0,duration-ticksElapsed.current));},[tick,tradeActive,duration]);
 useEffect(()=>{const tx=profitTransactions[0];const id=tx?.contract_id??null;if(!id||id===lastClosed.current)return;const purchase=Number(tx?.purchase_time??0);const started=tradeStartedAt.current;if(!tradeActive||!started||purchase<started)return;lastClosed.current=id;const pnl=Number(tx.profit_loss??0);const exitSpot=String(tx.exit_spot??tx.exit_tick??tx.sell_price??'—');const finalDigit=exitSpot==='—'?'—':exitSpot.replace(/\D/g,'').slice(-1)||'—';setResult({id,pnl,exitSpot,finalDigit,chosenDigit:digit,contractType});setTradeActive(false);setCountdown(0);playSound(pnl>=0?'win':'loss');},[profitTransactions,tradeActive,digit,contractType]);
 useEffect(()=>{if(error&&tradeActive&&!buying){setTradeActive(false);setCountdown(duration);ticksElapsed.current=0}},[error,tradeActive,buying,duration]);
 useEffect(()=>{try{const saved=sessionStorage.getItem('mozhyper-goals');if(saved){const p=JSON.parse(saved);const g=Number(p?.g);const l=Number(p?.l);if(Number.isFinite(g)&&g>0){setGainGoal(g);setGainGoalText(String(g))}if(Number.isFinite(l)&&l>0){setLossGoal(l);setLossGoalText(String(l))}}}catch{}},[]);
 const toMzn=(usd:number)=>usd*USD_TO_MZN;const fmtMzn=(usd:number)=>`${toMzn(usd).toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2})} MT`;
 const balanceText=balance?fmtMzn(Number(balance.balance)):'—';const liveLastDigit=tick?String(tick.quote).replace(/\D/g,'').slice(-1)||'—':'—';
 const totalPnl=useMemo(()=>profitTransactions.reduce((s,tx)=>s+Number(tx.profit_loss??0),0),[profitTransactions]);const last=profitTransactions[0];const lastPnl=Number(last?.profit_loss??0);const history=profitTransactions.slice(0,12);const lastTime=last?new Date(Number(last.sell_time||last.purchase_time)*1000).toLocaleTimeString():'—';const goalProfitMzn=toMzn(totalPnl);
 const labels:Record<ContractChoice,string>=language==='pt'?{MATCH:t('match'),DIFFERS:t('differs'),OVER:t('over'),UNDER:t('under'),EVEN:t('even'),ODD:t('odd')}:language==='es'?{MATCH:t('match'),DIFFERS:t('differs'),OVER:t('over'),UNDER:t('under'),EVEN:t('even'),ODD:t('odd')}:{MATCH:t('match'),DIFFERS:t('differs'),OVER:t('over'),UNDER:t('under'),EVEN:t('even'),ODD:t('odd')};
 const place=()=>{if(!proposal||!isAuthorized||buying||tradeActive||Number(proposal.ask_price)<MIN_STAKE)return;unlockAudio();playSound('buy');setResult(null);setGoalPopup(null);setTradeActive(true);tradeStartedAt.current=Math.floor(Date.now()/1000);ticksElapsed.current=0;setCountdown(duration);lastTick.current=tick?.epoch??null;buy(proposal.id,proposal.ask_price)};
 const normalize=()=>{const n=Number(amountText.replace(',','.'));const safe=Number.isFinite(n)?Math.max(MIN_STAKE,n):MIN_STAKE;setAmount(safe);setAmountText(safe.toFixed(2))};
 const selectDigit=(v:number)=>{if(!tradeActive)setDigit(v)};
 const selectSymbol=(s:string)=>{if(tradeActive)return;setSymbol(s);setSymbolOpen(false);setCountdown(duration);ticksElapsed.current=0};
 const saveGoals=()=>{const g=Number(gainGoalText.replace(',','.'));const l=Number(lossGoalText.replace(',','.'));const sg=Number.isFinite(g)&&g>0?g:null;const sl=Number.isFinite(l)&&l>0?l:null;setGainGoal(sg);setLossGoal(sl);setGoalNotified(false);try{sessionStorage.setItem('mozhyper-goals',JSON.stringify({g:sg,l:sl}))}catch{}setGoalsOpen(false)};
 useEffect(()=>{if(goalNotified)return;const hitGain=gainGoal!==null&&goalProfitMzn>=gainGoal;const hitLoss=lossGoal!==null&&goalProfitMzn<=-lossGoal;if(hitGain||hitLoss){setGoalNotified(true);setGoalPopup({id:Date.now(),target:hitGain?gainGoal!:lossGoal!,kind:hitGain?'gain':'loss'});playSound('goal')}},[goalProfitMzn,gainGoal,lossGoal,goalNotified]);
 const logout=()=>{try{sessionStorage.removeItem('mozhyper-goals')}catch{};setResult(null);setGoalPopup(null);window.location.assign('/api/auth/logout')};
 const cashier=()=>window.open('https://app.deriv.com/cashier','_blank','noopener,noreferrer');
 return <div className="matos-screen"><style jsx global>{`
 :root[data-theme='light']{--bg:#f3f6fb;--s1:#fff;--s2:#e9eef7;--s3:#dce5f5;--t1:#111827;--t2:#526174;--t3:#78869a}
 .result-popup{position:relative;margin:10px 12px;padding:14px 16px;border-radius:15px;text-align:center;background:var(--s2);border:1px solid rgba(255,255,255,.1);box-shadow:0 10px 30px rgba(0,0,0,.22);animation:resultIn .22s ease}.result-popup.win{border-color:rgba(52,211,153,.5)}.result-popup.loss{border-color:rgba(248,113,113,.5)}.result-popup-value{font:900 21px 'JetBrains Mono'}.result-popup.win .result-popup-value{color:#34d399}.result-popup.loss .result-popup-value{color:#f87171}.result-details{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:10px;text-align:left;font-size:11px}.result-details b{font-weight:800}.goal-popup{position:relative;margin:10px 12px;padding:13px 16px;border-radius:15px;text-align:center;background:var(--s2);border:1px solid rgba(250,204,21,.55);box-shadow:0 10px 30px rgba(0,0,0,.22);animation:resultIn .22s ease}.goals-btn{position:absolute;left:-85px;top:50%;transform:translateY(-50%);padding:10px 12px;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:var(--s2);color:var(--t1);font-weight:800;font-size:11px;white-space:nowrap}.goals-panel{position:absolute;left:-8px;top:calc(50% + 40px);width:245px;background:var(--s2);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:14px;z-index:30;box-shadow:0 18px 45px rgba(0,0,0,.35)}.goals-panel input{width:100%;margin:5px 0 10px;padding:10px;border-radius:9px;border:1px solid rgba(128,128,128,.2);background:var(--s1);color:var(--t1)}.goals-panel button.save{width:100%;padding:10px;border:0;border-radius:9px;background:var(--blue);color:#fff;font-weight:800}.loss-value{color:#f87171!important}.deriv-word{color:#ef4444!important}@keyframes resultIn{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}
 `}</style>
 {goalPopup&&<div className="goal-popup"><div style={{fontWeight:900,fontSize:16}}>{t('goalReached')}</div><div style={{marginTop:4}}>{t('goalReachedText')} <b>{goalPopup.target} MT</b></div><div style={{fontSize:11,opacity:.7,marginTop:4}}>{t('meta')}</div></div>}
 {result&&<div className={`result-popup ${result.pnl>=0?'win':'loss'}`}><div style={{fontWeight:900}}>{result.pnl>=0?'✓':'✕'} {result.pnl>=0?t('win'):t('loss')} — {t('contractClosed')}</div><div className="result-popup-value">{result.pnl>=0?'+':''}{fmtMzn(result.pnl)}</div><div className="result-details"><span>{t('chosen')}: <b>{result.chosenDigit}</b></span><span>{t('cameOut')}: <b>{result.finalDigit}</b></span><span>{t('finalTick')}: <b>{result.exitSpot}</b></span><span>{result.pnl>=0?'✓': '❌'} {result.pnl>=0?t('win'):t('lost')}</span></div></div>}
 <div className="matos-top"><div className="brand"><div className="avatar">M</div><div className="brand-name">Moz<span>Hyper</span></div></div><div className="top-actions"><div className="menu-wrap"><button className="menu-btn" aria-label="Menu" onClick={()=>setMenuOpen(v=>!v)}>•••</button>{menuOpen&&<div className="menu settings-menu"><div className="menu-title">{t('language')}</div><div className="menu-langs"><button className={language==='en'?'active':''} onClick={()=>{setLanguage('en');setMenuOpen(false)}}>🇬🇧 EN</button><button className={language==='pt'?'active':''} onClick={()=>{setLanguage('pt');setMenuOpen(false)}}>🇵🇹 PT</button><button className={language==='es'?'active':''} onClick={()=>{setLanguage('es');setMenuOpen(false)}}>🇪🇸 ES</button></div><div className="menu-sep"/><button onClick={()=>{cashier();setMenuOpen(false)}}>↓ {language==='pt'?'Depositar':language==='es'?'Depositar':'Deposit'}</button><button onClick={()=>{cashier();setMenuOpen(false)}}>↑ {language==='pt'?'Levantar':language==='es'?'Retirar':'Withdraw'}</button></div>}</div><button className="logout" onClick={logout}>{t('logout')}</button></div></div>
 <div className="stats"><div className="stat"><div className="stat-label">{t('balance')}</div><div className="stat-value">{balanceText}</div></div><div className="stat-divider"/><div className="stat"><div className="stat-label">{t('profitLoss')}</div><div className={`stat-value ${totalPnl>=0?'profit':'loss-value'}`}>{totalPnl>=0?'+':''}{fmtMzn(totalPnl)}</div></div></div>
 <div className="control-row"><div><div className="control-label">{language==='pt'?'Tipo de Conta':language==='es'?'Tipo de Cuenta':'Account Type'}</div><div className="control-pill real">{balance?.loginid?.startsWith('CR')?'REAL':'DEMO'} <span>⟳</span></div></div><div><div className="control-label">{t('contractType')}</div><div className="control-pill" onClick={()=>setPredictionOpen(v=>!v)}>{labels[contractType]} <span>⌄</span>{predictionOpen&&<div className="select-menu" onClick={e=>e.stopPropagation()}>{(Object.keys(CONTRACT_TYPES) as ContractChoice[]).map(k=><button key={k} onClick={()=>{if(!tradeActive){setContractType(k);setPredictionOpen(false)}}}>{labels[k]}</button>)}</div>}</div></div><div><div className="control-label">{t('videoTutorial')}</div><button className="control-pill video" onClick={()=>document.getElementById('tutorial')?.scrollIntoView({behavior:'smooth'})}>▶ <span>ⓘ</span></button></div></div>
 <div className="last-op"><div className="last-op-head"><span className="history-label" style={{margin:0}}>{language==='pt'?'Última operação fechada':language==='es'?'Última operación cerrada':'Last closed operation'}</span><span className="last-op-time">{lastTime}</span></div><div className="last-op-grid"><div className="last-op-cell"><span>{t('type')}</span><span>{last?.contract_type?labels[(Object.keys(CONTRACT_TYPES) as ContractChoice[]).find(k=>CONTRACT_TYPES[k]===last.contract_type)??'MATCH']:'—'}</span></div><div className="last-op-cell"><span>{t('finalTick')}</span><span>{last?.exit_spot??last?.exit_tick??'—'}</span></div><div className="last-op-cell"><span>{t('buyPrice')}</span><span>{last?Number(last.buy_price).toFixed(2):'—'} USD</span></div><div className="last-op-cell"><span>{t('result')}</span><span className={lastPnl>=0?'profit':'loss-value'}>{last?`${lastPnl>=0?'+':''}${fmtMzn(lastPnl)}`:'—'}</span></div></div></div>
 <div className="dial" style={{position:'relative'}}><button className="goals-btn" onClick={()=>setGoalsOpen(v=>!v)}>🎯 {t('meta')}</button>{goalsOpen&&<div className="goals-panel"><b>{t('meta')} (MT)</b><div style={{fontSize:10,color:'var(--t3)',marginTop:4}}>Defina a meta da sessão.</div><label style={{fontSize:10}}>{t('profit')}</label><input inputMode="decimal" value={gainGoalText} onChange={e=>setGainGoalText(e.target.value)} placeholder="10"/><label style={{fontSize:10}}>{t('lossGoal')}</label><input inputMode="decimal" value={lossGoalText} onChange={e=>setLossGoalText(e.target.value)} placeholder="50"/><button className="save" onClick={saveGoals}>{t('save')}</button></div>}
 <div className="dial-ring"/>{PROBS.map((p,i)=>{const a=i/10*Math.PI*2-Math.PI/2,r=103,x=124+r*Math.cos(a),y=124+r*Math.sin(a);return <button key={i} className={`digit ${i===digit?'active':''}`} style={{left:x,top:y}} onClick={()=>selectDigit(i)}><span className="n">{i}</span><span className="p">{p.toFixed(1)}%</span></button>})}<div className="dial-center"><div className="dial-last-digit">{liveLastDigit}</div><div className="dial-label">{t('lastDigit')}</div></div></div>
 <div className="countdown trade-countdown" aria-live="polite">{countdown}</div>
 <div className="section-label">{t('stake')} <span>mínimo: $1.50 USD</span></div><div className="stake-input-wrap"><span>USD</span><input inputMode="decimal" type="text" value={amountText} onChange={e=>{const v=e.target.value.replace(',','.');setAmountText(v);const n=Number(v);if(Number.isFinite(n)&&n>=MIN_STAKE)setAmount(n)}} onBlur={normalize}/></div>
 {error&&<div className="error-box">⚠️ {error}</div>}<button className="cta" onClick={place} disabled={!proposal||!isAuthorized||buying||tradeActive}>{buying?`⏳ ${t('buying')}`:`🎯 ${t('buy')}`}{proposal&&<small> · +{fmtMzn(Number(proposal.payout-proposal.ask_price))}</small>}</button>{!isAuthorized&&<div className="error-box" style={{marginTop:10,marginBottom:0}}>{t('unauthorizedWarning')}</div>}
 <div className="history-label">{t('recentHistory')}</div><div className="history">{history.length===0&&<span style={{color:'var(--t3)',fontSize:10}}>{t('waitingTick')}</span>}{history.map(tx=>{const pnl=Number(tx.profit_loss??0);const key=(Object.keys(CONTRACT_TYPES) as ContractChoice[]).find(k=>CONTRACT_TYPES[k]===tx.contract_type)??'MATCH';return <div key={tx.contract_id} className={`history-chip ${pnl>=0?'win':'loss'}`}><div>{pnl>=0?'+':''}{fmtMzn(pnl)}</div><div>{labels[key]}</div></div>})}</div>
 <div className="market-controls"><div className="section-label">{t('symbol')}</div><div className="symbol-select-wrap"><button className="symbol-select" onClick={()=>setSymbolOpen(v=>!v)}>{SYMBOLS[symbol]} <span>⌄</span></button>{symbolOpen&&<div className="symbol-menu">{Object.entries(SYMBOLS).map(([v,l])=><button key={v} onClick={()=>selectSymbol(v)}>{l}</button>)}</div>}</div><div className="section-label duration-label">{t('duration')} <span>ticks</span></div><div className="duration-row"><button className={`duration ${duration===1?'active':''}`} onClick={()=>{if(!tradeActive){setDuration(1);setCountdown(1);ticksElapsed.current=0}}}>1 tick</button><button className={`duration ${duration===5?'active':''}`} onClick={()=>{if(!tradeActive){setDuration(5);setCountdown(5);ticksElapsed.current=0}}}>5 ticks</button></div></div>
 <div className="footer-note">Powered by <span className="deriv-word">Deriv</span> · {language==='pt'?'Jogue com responsabilidade':language==='es'?'Juega responsablemente':'Play responsibly'}</div>
 </div>;
}
