'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useDeriv } from '@/hooks/useDeriv';
import { useLanguage } from '@/contexts/LanguageContext';

const CONTRACT_TYPES = { OVER:'DIGITOVER', UNDER:'DIGITUNDER', MATCH:'DIGITMATCH', DIFFERS:'DIGITDIFF', EVEN:'DIGITEVEN', ODD:'DIGITODD' } as const;
type ContractChoice = keyof typeof CONTRACT_TYPES;
const SYMBOLS: Record<string,string> = { R_100:'Volatility 100 Index', R_50:'Volatility 50 Index', R_10:'Volatility 10 Index', R_25:'Volatility 25 Index', R_75:'Volatility 75 Index', '1HZ100V':'Volatility 100 (1s) Index', '1HZ50V':'Volatility 50 (1s) Index' };
const PROBS = [10,10,10,10,10,10,10,10,10,10];
const MIN_STAKE = 1.50;
const USD_TO_MZN = 68;
type Theme = 'dark'|'light';
type AudioWindow = Window & { webkitAudioContext?: typeof AudioContext };
let audioCtx: AudioContext | null = null;
let audioUnlocked = false;

function unlockAudio(){ if(typeof window==='undefined') return; try{ const AC=window.AudioContext || (window as AudioWindow).webkitAudioContext; if(!AC)return; if(!audioCtx)audioCtx=new AC(); if(audioCtx.state==='suspended')void audioCtx.resume(); audioUnlocked=true; }catch{} }
function playSound(kind:'tick'|'buy'|'win'|'loss'|'goal'){ if(typeof window==='undefined')return; try{unlockAudio();if(!audioCtx||!audioUnlocked)return;const notes=kind==='win'?[523.25,659.25,783.99,1046.5]:kind==='goal'?[659.25,783.99,1046.5,1318.51]:kind==='loss'?[440,349.23,261.63]:kind==='buy'?[520,760]:[620];const now=audioCtx.currentTime;const step=kind==='win'||kind==='goal'?.075:.08;notes.forEach((freq,i)=>{const osc=audioCtx!.createOscillator();const gain=audioCtx!.createGain();osc.type=kind==='loss'?'sawtooth':'sine';osc.frequency.setValueAtTime(freq,now+i*step);gain.gain.setValueAtTime(.0001,now+i*step);gain.gain.exponentialRampToValueAtTime(kind==='tick'?.05:.095,now+i*step+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+i*step+.15);osc.connect(gain);gain.connect(audioCtx!.destination);osc.start(now+i*step);osc.stop(now+i*step+.17);});}catch{} }

export default function DigitsGameV3(){
 const {t,language,setLanguage}=useLanguage();
 const {balance,tick,proposal,buying,getProposal,buy,subscribeTicks,isAuthorized,isConnected,error,profitTransactions}=useDeriv();
 const [contractType,setContractType]=useState<ContractChoice>('MATCH');
 const [amount,setAmount]=useState(MIN_STAKE); const [amountText,setAmountText]=useState('1.50');
 const [symbol,setSymbol]=useState('R_100'); const [symbolOpen,setSymbolOpen]=useState(false); const [digit,setDigit]=useState(5); const [predictionOpen,setPredictionOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false);
 const [duration,setDuration]=useState(1); const [countdown,setCountdown]=useState(1); const [tradeActive,setTradeActive]=useState(false);
 const [theme,setTheme]=useState<Theme>(()=>typeof window!=='undefined'&&localStorage.getItem('mozhyper-theme')==='light'?'light':'dark'); const [popup,setPopup]=useState<{id:number;pnl:number;digit:string}|null>(null);
 const [goalsOpen,setGoalsOpen]=useState(false); const [gainGoalText,setGainGoalText]=useState(''); const [lossGoalText,setLossGoalText]=useState(''); const [gainGoal,setGainGoal]=useState<number|null>(null); const [lossGoal,setLossGoal]=useState<number|null>(null); const [goalNotified,setGoalNotified]=useState(false);
 const [frozenFinalDigit,setFrozenFinalDigit]=useState<string|null>(null); const lastTick=useRef<number|null>(null); const lastClosed=useRef<number|null>(null); const ticksElapsed=useRef(0);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('mozhyper-theme',theme)},[theme]);
 useEffect(()=>{const activate=()=>unlockAudio();window.addEventListener('pointerdown',activate,{passive:true});window.addEventListener('touchstart',activate,{passive:true});window.addEventListener('keydown',activate,{passive:true});return()=>{window.removeEventListener('pointerdown',activate);window.removeEventListener('touchstart',activate);window.removeEventListener('keydown',activate)}},[]);
 useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[symbol,isConnected,subscribeTicks]);
 useEffect(()=>{if(isAuthorized&&isConnected&&!tradeActive)getProposal(symbol,CONTRACT_TYPES[contractType],Math.max(MIN_STAKE,amount),duration,digit)},[contractType,amount,digit,symbol,duration,isAuthorized,isConnected,tradeActive,getProposal]);
 useEffect(()=>{if(!tradeActive||!tick?.epoch||lastTick.current===tick.epoch)return;lastTick.current=tick.epoch;ticksElapsed.current=Math.min(duration,ticksElapsed.current+1);playSound('tick');setCountdown(Math.max(0,duration-ticksElapsed.current));},[tick,tradeActive,duration]);
 useEffect(()=>{const tx=profitTransactions[0];const id=tx?.contract_id??null;if(id&&id!==lastClosed.current){lastClosed.current=id;const pnl=Number(tx.profit_loss??0);const finalTick=tx.exit_tick??tx.sell_price??'—';const closedDigit=String(finalTick).replace(/\D/g,'').slice(-1)||'—';setFrozenFinalDigit(closedDigit);setTradeActive(false);setCountdown(0);setPopup({id,pnl,digit:closedDigit});playSound(pnl>=0?'win':'loss');window.setTimeout(()=>{setPopup(p=>p?.id===id?null:p);setFrozenFinalDigit(current=>current===closedDigit?null:current);setCountdown(duration)},5000);}},[profitTransactions,duration]);
 useEffect(()=>{if(error&&tradeActive&&!buying){setTradeActive(false);setCountdown(duration);ticksElapsed.current=0}},[error,tradeActive,buying,duration]);
 useEffect(()=>{if(typeof window==='undefined')return;const onVisible=()=>{if(document.visibilityState==='visible'){unlockAudio();if(isConnected)subscribeTicks(symbol)}};document.addEventListener('visibilitychange',onVisible);window.addEventListener('focus',onVisible);return()=>{document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('focus',onVisible)}},[isConnected,symbol,subscribeTicks]);
 useEffect(()=>{try{const saved=sessionStorage.getItem('mozhyper-goals');if(saved){const parsed=JSON.parse(saved);const g=Number(parsed?.g);const l=Number(parsed?.l);if(Number.isFinite(g)&&g>0){setGainGoal(g);setGainGoalText(String(g))}if(Number.isFinite(l)&&l>0){setLossGoal(l);setLossGoalText(String(l))}}}catch{}},[]);
 const toMzn=(usd:number)=>usd*USD_TO_MZN; const fmtMzn=(usd:number)=>`${toMzn(usd).toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2})} MT`;
 const balanceText=balance?fmtMzn(Number(balance.balance)):'—'; const liveLastDigit=tick?String(tick.quote).replace(/\D/g,'').slice(-1)||'—':'—'; const displayedDigit=frozenFinalDigit??liveLastDigit;
 const totalPnl=useMemo(()=>profitTransactions.reduce((sum,tx)=>sum+Number(tx.profit_loss??0),0),[profitTransactions]); const last=profitTransactions[0]; const lastPnl=Number(last?.profit_loss??0); const history=profitTransactions.slice(0,12); const lastTime=last?new Date((last.sell_time||last.purchase_time)*1000).toLocaleTimeString():'—'; const goalProfitMzn=toMzn(totalPnl);
 const labels:Record<ContractChoice,string>=language==='pt'?{MATCH:'Igual',DIFFERS:'Diferente',OVER:'Acima',UNDER:'Abaixo',EVEN:'Par',ODD:'Ímpar'}:language==='es'?{MATCH:'Igual',DIFFERS:'Diferente',OVER:'Superior',UNDER:'Inferior',EVEN:'Par',ODD:'Impar'}:{MATCH:'Matches',DIFFERS:'Differs',OVER:'Over',UNDER:'Under',EVEN:'Even',ODD:'Odd'};
 const place=()=>{if(!proposal||!isAuthorized||buying||tradeActive||Number(proposal.ask_price)<MIN_STAKE)return;unlockAudio();playSound('buy');setFrozenFinalDigit(null);setTradeActive(true);ticksElapsed.current=0;setCountdown(duration);lastTick.current=tick?.epoch??null;buy(proposal.id,proposal.ask_price)};
 const normalize=()=>{const n=Number(amountText.replace(',','.'));const safe=Number.isFinite(n)?Math.max(MIN_STAKE,n):MIN_STAKE;setAmount(safe);setAmountText(safe.toString())};
 const selectDigit=(value:number)=>{if(tradeActive)return;setFrozenFinalDigit(null);setDigit(value)};
 const selectSymbol=(s:string)=>{setSymbol(s);setSymbolOpen(false);setTradeActive(false);setFrozenFinalDigit(null);ticksElapsed.current=0;setCountdown(duration)};
 const logout=()=>{try{sessionStorage.removeItem('mozhyper-goals')}catch{};window.location.assign('/api/auth/logout')};
 const cashier=()=>window.open('https://app.deriv.com/cashier','_blank','noopener,noreferrer'); const support=()=>window.open('https://track.deriv.com/_xhgntjGPYQ7xidYl18iLj2Nd7ZgqdRLk/1/','_blank','noopener,noreferrer');
 const predictionLabel=labels[contractType]; const saveGoals=()=>{const g=Number(gainGoalText.replace(',','.'));const l=Number(lossGoalText.replace(',','.'));const safeG=Number.isFinite(g)&&g>0?g:null;const safeL=Number.isFinite(l)&&l>0?l:null;setGainGoal(safeG);setLossGoal(safeL);try{sessionStorage.setItem('mozhyper-goals',JSON.stringify({g:safeG,l:safeL}))}catch{};setGoalsOpen(false);setGoalNotified(false)};
 useEffect(()=>{if(goalNotified)return;const hitGain=gainGoal!==null&&goalProfitMzn>=gainGoal;const hitLoss=lossGoal!==null&&goalProfitMzn<=-lossGoal;if(hitGain||hitLoss){setGoalNotified(true);playSound('goal');const id=Date.now();setPopup({id,pnl:totalPnl,digit:displayedDigit});window.setTimeout(()=>setPopup(p=>p?.id===id?null:p),5000)}},[goalProfitMzn,gainGoal,lossGoal,goalNotified,totalPnl,displayedDigit]);
 return <div className="matos-screen"><style jsx global>{`
 :root[data-theme='light']{--bg:#f3f6fb;--s1:#fff;--s2:#e9eef7;--s3:#dce5f5;--t1:#111827;--t2:#526174;--t3:#78869a}
 .matos-screen{min-height:100dvh;width:100%;max-width:480px;margin:0 auto;padding:0;overflow-x:hidden}.settings-menu{width:220px;padding:8px}.menu-title{padding:7px 8px 5px;color:var(--t3);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.menu-langs,.theme-toggle{display:flex;gap:5px;padding:0 2px 7px}.menu-langs button,.theme-toggle button{flex:1!important;text-align:center!important;padding:8px 4px!important;background:var(--s1)!important;color:var(--t2)!important}.menu-langs button.active,.theme-toggle button.active{background:var(--blue)!important;color:#fff!important}.menu-sep{height:1px;background:rgba(128,128,128,.18);margin:4px 0}.result-popup{position:fixed;z-index:100;left:50%;top:18px;transform:translateX(-50%);min-width:240px;padding:13px 18px;border-radius:15px;text-align:center;background:var(--s2);border:1px solid rgba(255,255,255,.1);box-shadow:0 18px 45px rgba(0,0,0,.35);animation:resultIn .22s ease}.result-popup.win{border-color:rgba(52,211,153,.45)}.result-popup.loss{border-color:rgba(248,113,113,.45)}.result-popup-value{font:800 20px 'JetBrains Mono'}.result-popup.win .result-popup-value{color:var(--win)}.result-popup.loss .result-popup-value{color:var(--loss)}.deriv-word{color:#ef4444!important}.loss-value{color:#f87171!important}.support-btn{color:#fff!important;background:var(--blue)!important}.goals-btn{position:absolute;left:-120px;top:50%;transform:translateY(-50%);padding:11px 14px;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:var(--s2);color:var(--t1);font-weight:800;font-size:11px;white-space:nowrap;cursor:pointer}.goals-panel{position:absolute;left:-10px;top:calc(50% + 42px);width:245px;background:var(--s2);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:14px;z-index:30;box-shadow:0 18px 45px rgba(0,0,0,.35)}.goals-panel input{width:100%;margin:5px 0 10px;padding:10px;border-radius:9px;border:1px solid rgba(128,128,128,.2);background:var(--s1);color:var(--t1)}.goals-panel button.save{width:100%;padding:10px;border:0;border-radius:9px;background:var(--blue);color:#fff;font-weight:800}.parity-note{font-size:10px;color:var(--t3)}
 @keyframes resultIn{from{opacity:0;transform:translate(-50%,-10px)}to{opacity:1;transform:translate(-50%,0)}}
 `}</style>
 {popup&&<div className={`result-popup ${popup.pnl>=0?'win':'loss'}`}><div className="result-popup-title">{popup.pnl>=0?'✓':'✕'} {language==='pt'?'Contrato fechado':'Contract closed'}</div><div className="result-popup-value">{popup.pnl>=0?'+':''}{fmtMzn(popup.pnl)}</div><div style={{fontSize:11,marginTop:4}}>{language==='pt'?'Último dígito':'Last digit'}: <b>{popup.digit}</b></div></div>}
 <div className="matos-top"><div className="brand"><div className="avatar">M</div><div className="brand-name">Moz<span>Hyper</span></div></div><div className="top-actions"><div className="menu-wrap"><button className="menu-btn" aria-label="Menu" onClick={()=>setMenuOpen(v=>!v)}>•••</button>{menuOpen&&<div className="menu settings-menu"><div className="menu-title">{language==='pt'?'Idioma':'Language'}</div><div className="menu-langs"><button className={language==='en'?'active':''} onClick={()=>{setLanguage('en');setMenuOpen(false)}}>EN</button><button className={language==='pt'?'active':''} onClick={()=>{setLanguage('pt');setMenuOpen(false)}}>PT</button><button className={language==='es'?'active':''} onClick={()=>{setLanguage('es');setMenuOpen(false)}}>ES</button></div><div className="menu-title">{language==='pt'?'Tema':'Theme'}</div><div className="theme-toggle"><button className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}>🌙 Dark</button><button className={theme==='light'?'active':''} onClick={()=>setTheme('light')}>☀️ Light</button></div><div className="menu-sep"/><button onClick={()=>{cashier();setMenuOpen(false)}}>↓ {language==='pt'?'Depositar':'Deposit'}</button><button onClick={()=>{cashier();setMenuOpen(false)}}>↑ {language==='pt'?'Levantar':'Withdraw'}</button><button className="support-btn" onClick={()=>{support();setMenuOpen(false)}}>🛟 {language==='pt'?'Suporte':'Support'}</button></div>}</div><button className="logout" onClick={logout}>{t('logout')}</button></div></div>
 <div className="stats"><div className="stat"><div className="stat-label">{t('balance')}</div><div className="stat-value">{balanceText}</div></div><div className="stat-divider"/><div className="stat"><div className="stat-label">{t('profitLoss')}</div><div className={`stat-value ${totalPnl>=0?'profit':'loss-value'}`}>{totalPnl>=0?'+':''}{fmtMzn(totalPnl)}</div></div></div>
 <div className="control-row"><div><div className="control-label">{language==='pt'?'Tipo de Conta':'Account Type'}</div><div className="control-pill real">{balance?.loginid?.startsWith('CR')?'REAL':'DEMO'} <span>⟳</span></div></div><div><div className="control-label">{language==='pt'?'Tipo de Previsão':'Prediction Type'}</div><div className="control-pill" onClick={()=>setPredictionOpen(v=>!v)}>{predictionLabel} <span>⌄</span>{predictionOpen&&<div className="select-menu" onClick={e=>e.stopPropagation()}>{(Object.keys(CONTRACT_TYPES) as ContractChoice[]).map(k=><button key={k} onClick={()=>{setContractType(k);setPredictionOpen(false)}}>{labels[k]}</button>)}</div>}</div></div><div><div className="control-label">{language==='pt'?'Vídeo Aula':'Tutorial'}</div><button className="control-pill video" onClick={()=>document.getElementById('tutorial')?.scrollIntoView({behavior:'smooth'})}>▶ <span>ⓘ</span></button></div></div>
 <div className="last-op"><div className="last-op-head"><span className="history-label" style={{margin:0}}>{language==='pt'?'Última operação fechada':'Last closed operation'}</span><span className="last-op-time">{lastTime}</span></div><div className="last-op-grid"><div className="last-op-cell"><span>{t('type')}</span><span>{last?.contract_type||'—'}</span></div><div className="last-op-cell"><span>{language==='pt'?'Tick Final':'Final Tick'}</span><span>{last?.exit_tick??last?.sell_price??'—'}</span></div><div className="last-op-cell"><span>{language==='pt'?'Preço':'Price'}</span><span>{last?Number(last.buy_price).toFixed(2):'—'} USD</span></div><div className="last-op-cell"><span>{language==='pt'?'Resultado':'Result'}</span><span className={lastPnl>=0?'profit':'loss-value'}>{last?`${lastPnl>=0?'+':''}${fmtMzn(lastPnl)}`:'—'}</span></div></div></div>
 <div className="dial" style={{position:'relative'}}><button className="goals-btn" onClick={()=>setGoalsOpen(v=>!v)}>🎯 {language==='pt'?'Metas diárias':'Daily goals'}</button>{goalsOpen&&<div className="goals-panel"><b>{language==='pt'?'Metas diárias (MT)':'Daily goals (MZN)'}</b><div style={{fontSize:10,color:'var(--t3)',marginTop:4}}>{language==='pt'?'Deixe vazio para não usar limites.':'Leave empty to disable.'}</div><label style={{fontSize:10}}>{language==='pt'?'Meta de ganho':'Profit goal'}</label><input inputMode="decimal" value={gainGoalText} onChange={e=>setGainGoalText(e.target.value)} placeholder="Ex.: 1000"/><label style={{fontSize:10}}>{language==='pt'?'Meta de perdas':'Loss goal'}</label><input inputMode="decimal" value={lossGoalText} onChange={e=>setLossGoalText(e.target.value)} placeholder="Ex.: 500"/><button className="save" onClick={saveGoals}>{language==='pt'?'Guardar metas':'Save goals'}</button></div>}
 <div className="dial-ring"/>{PROBS.map((p,i)=>{const a=i/10*Math.PI*2-Math.PI/2,r=103,x=124+r*Math.cos(a),y=124+r*Math.sin(a);return <button key={i} className={`digit ${i===digit?'active':''}`} style={{left:x,top:y}} onClick={()=>selectDigit(i)}><span className="n">{i}</span><span className="p">{p.toFixed(1)}%</span></button>})}<div className="dial-center"><div className="dial-last-digit">{displayedDigit}</div><div className="dial-label">{language==='pt'?'último dígito':'last digit'}</div></div></div>
 <div className="countdown trade-countdown" aria-live="polite">{countdown}</div>
 <div className="section-label">{language==='pt'?'Aposta':'Stake'} <span>mínimo: $1.50 USD</span></div><div className="stake-input-wrap"><span>USD</span><input inputMode="decimal" type="text" value={amountText} onChange={e=>{const v=e.target.value.replace(',','.');setAmountText(v);const n=Number(v);if(Number.isFinite(n)&&n>=MIN_STAKE)setAmount(n)}} onBlur={normalize} aria-label="Stake USD"/></div>
 {error&&<div className="error-box">⚠️ {error}</div>}<button className="cta" onClick={place} disabled={!proposal||!isAuthorized||buying||tradeActive}>{buying?`⏳ ${t('buying')}`:language==='pt'?'🎯 Colocar previsão':'🎯 Place prediction'}{proposal&&<small> · +{fmtMzn(Number(proposal.payout-proposal.ask_price))}</small>}</button>{!isAuthorized&&<div className="error-box" style={{marginTop:10,marginBottom:0}}>{t('unauthorizedWarning')}</div>}
 <div className="history-label">{language==='pt'?'Histórico recente':'Recent history'}</div><div className="history">{history.length===0&&<span style={{color:'var(--t3)',fontSize:10}}>{t('waitingTick')}</span>}{history.map(tx=>{const pnl=Number(tx.profit_loss??0);return <div key={tx.contract_id} className={`history-chip ${pnl>=0?'win':'loss'}`}><div>{pnl>=0?'+':''}{fmtMzn(pnl)}</div><div>{tx.contract_type==='DIGITMATCH'?labels.MATCH:tx.contract_type==='DIGITDIFF'?labels.DIFFERS:tx.contract_type==='DIGITOVER'?labels.OVER:tx.contract_type==='DIGITUNDER'?labels.UNDER:tx.contract_type==='DIGITEVEN'?labels.EVEN:labels.ODD}</div></div>})}</div>
 <div className="market-controls"><div className="section-label">{t('symbol')}</div><div className="symbol-select-wrap"><button className="symbol-select" onClick={()=>setSymbolOpen(v=>!v)}>{SYMBOLS[symbol]} <span>⌄</span></button>{symbolOpen&&<div className="symbol-menu">{Object.entries(SYMBOLS).map(([v,l])=><button key={v} onClick={()=>selectSymbol(v)}>{l}</button>)}</div>}</div><div className="section-label duration-label">{language==='pt'?'Duração':'Duration'} <span>ticks</span></div><div className="duration-row"><button className={`duration ${duration===1?'active':''}`} onClick={()=>{if(!tradeActive){setDuration(1);setCountdown(1);ticksElapsed.current=0}}}>1 tick</button><button className={`duration ${duration===5?'active':''}`} onClick={()=>{if(!tradeActive){setDuration(5);setCountdown(5);ticksElapsed.current=0}}}>5 ticks</button></div></div>
 <div className="footer-note">Powered by <span className="deriv-word">Deriv</span> · {language==='pt'?'Jogue com responsabilidade':'Play responsibly'}</div>
 </div>;
}
