'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useDeriv} from '@/hooks/useDeriv';
const SYMBOLS:Record<string,string>={R_10:'Volatility 10 Index',R_25:'Volatility 25 Index',R_50:'Volatility 50 Index',R_75:'Volatility 75 Index',R_100:'Volatility 100 Index','1HZ10V':'Volatility 10 (1s) Index','1HZ25V':'Volatility 25 (1s) Index','1HZ50V':'Volatility 50 (1s) Index','1HZ75V':'Volatility 75 (1s) Index','1HZ100V':'Volatility 100 (1s) Index'};
const USD_MZN=68;
function digit(v:any){const s=String(v??'').replace(/\D/g,'');return s?Number(s.slice(-1)):null}
export default function IAHyper1(){
 const[symbol,setSymbol]=useState('1HZ100V'),[account,setAccount]=useState<'demo'|'real'>('demo'),[stake,setStake]=useState(1),[target,setTarget]=useState(680),[stop,setStop]=useState(88),[running,setRunning]=useState(false),[digits,setDigits]=useState<number[]>([]),[direction,setDirection]=useState<'EVEN'|'ODD'|null>(null),[nextStake,setNextStake]=useState(1),[soros,setSoros]=useState(0),[lastContract,setLastContract]=useState<number|null>(null);
 const epoch=useRef<number|null>(null),requested=useRef(false);
 const{tick,balance,proposal,buy,buying,activeContractId,getProposal,subscribeTicks,isAuthorized,isConnected,profitTransactions}=useDeriv(account);
 const profit=useMemo(()=>profitTransactions.reduce((s,x)=>s+Number(x.profit_loss||0),0),[profitTransactions]);
 useEffect(()=>{setNextStake(stake);setSoros(0);setDirection(null);setDigits([]);requested.current=false},[stake,symbol,account]);
 useEffect(()=>{if(isConnected)subscribeTicks(symbol)},[isConnected,symbol,subscribeTicks]);
 useEffect(()=>{if(!tick?.epoch||tick.epoch===epoch.current)return;epoch.current=tick.epoch;const d=digit(tick.quote);if(d===null)return;setDigits(v=>[d,...v].slice(0,10));if(running&&activeContractId===null&&!requested.current){setDigits(v=>{const next=[d,...v].slice(0,10);if(next.length>=2){const[a,b]=next;if(a%2===0&&b%2===0)setDirection('EVEN');else if(a%2!==0&&b%2!==0)setDirection('ODD');}return next})}},[tick,running,activeContractId]);
 useEffect(()=>{if(!running||!direction||!isAuthorized||!isConnected||requested.current||proposal||buying||activeContractId!==null)return;requested.current=true;if(!getProposal(symbol,direction==='EVEN'?'DIGITEVEN':'DIGITODD',Math.max(.5,nextStake),1,0))requested.current=false},[running,direction,isAuthorized,isConnected,proposal,buying,activeContractId,getProposal,symbol,nextStake]);
 useEffect(()=>{if(running&&proposal&&!buying&&activeContractId===null)buy(proposal.id,proposal.ask_price)},[running,proposal,buying,activeContractId,buy]);
 useEffect(()=>{requested.current=false;const x=profitTransactions[0];if(!x?.contract_id||x.contract_id===lastContract||x.sell_time==null)return;setLastContract(x.contract_id);const pl=Number(x.profit_loss||0);if(pl>=0){const newStake=Number((nextStake+pl).toFixed(2));if(soros+1>=3){setNextStake(stake);setSoros(0)}else{setNextStake(newStake);setSoros(v=>v+1)}}else{const mg=Number((nextStake*2.1).toFixed(2));if(mg<=0||Number(balance?.balance||0)-mg<(stop/USD_MZN)){setRunning(false);setNextStake(stake);setSoros(0)}else{setNextStake(mg);setSoros(0);setDirection(q=>q==='EVEN'?'ODD':'EVEN')}}},[profitTransactions,lastContract,nextStake,soros,stake,balance,stop]);
 useEffect(()=>{if(!running)return;if(profit*USD_MZN>=target||profit*USD_MZN<=-stop){setRunning(false);requested.current=false}},[profit,target,stop,running]);
 const start=()=>{if(!isAuthorized||!isConnected)return;setDigits([]);setDirection(null);setNextStake(stake);setSoros(0);setRunning(true);requested.current=false};
 return <div className="ia-hyper"><style>{`.ia-hyper{padding:10px;background:var(--bg);color:var(--t1);font-family:Inter,system-ui}.ia-card{background:var(--s1);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:12px;margin-bottom:8px}.ia-title{font-size:12px;font-weight:900}.ia-sub{font-size:8px;color:var(--t3);margin-top:3px}.ia-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ia-box{background:var(--s2);border-radius:10px;padding:9px}.ia-label{font-size:8px;color:var(--t3);font-weight:800}.ia-value{display:block;font-size:17px;font-weight:900;margin-top:4px}.ia-pos{color:#2fd480}.ia-neg{color:#f0495a}.ia-select,.ia-input{width:100%;margin-top:5px;background:var(--s2);border:0;border-radius:8px;padding:9px;color:var(--t1);font-size:10px;outline:none}.ia-btn{width:100%;border:0;border-radius:10px;padding:12px;background:#2563eb;color:#fff;font-weight:900}.ia-btn.stop{background:#d83b4b}.ia-digits{display:grid;grid-template-columns:repeat(10,1fr);gap:4px;margin-top:8px}.ia-digit{text-align:center;padding:7px 2px;background:var(--s2);border-radius:7px;font-size:10px}.ia-signal{text-align:center;padding:14px;border-radius:10px;background:var(--s2);font-size:18px;font-weight:900}.ia-history{max-height:160px;overflow:auto}.ia-row{display:flex;justify-content:space-between;padding:7px 0;border-top:1px solid rgba(255,255,255,.06);font-size:9px}`}</style>
 <div className="ia-card"><div className="ia-title">🤖 IA Hper1</div><div className="ia-sub">Sequência de 2 dígitos com a mesma paridade · Soros 3 níveis · Martingale único x2.1</div></div>
 <div className="ia-card ia-grid"><label><span className="ia-label">CONTA</span><select className="ia-select" value={account} onChange={e=>setAccount(e.target.value as 'demo'|'real')} disabled={running}><option value="demo">Demo</option><option value="real">Real</option></select></label><label><span className="ia-label">ÍNDICE</span><select className="ia-select" value={symbol} onChange={e=>setSymbol(e.target.value)} disabled={running}>{Object.entries(SYMBOLS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 <div className="ia-card ia-grid"><div className="ia-box"><span className="ia-label">SALDO</span><b className="ia-value">{balance?`${Number(balance.balance).toFixed(2)} ${balance.currency}`:'—'}</b></div><div className="ia-box"><span className="ia-label">LUCRO/PERDA</span><b className={`ia-value ${profit>=0?'ia-pos':'ia-neg'}`}>{profit>=0?'+':''}{(profit*USD_MZN).toFixed(0)} MT</b></div></div>
 <div className="ia-card ia-grid"><label><span className="ia-label">ENTRADA INICIAL USD</span><input className="ia-input" type="number" min="0.5" step="0.1" value={stake} onChange={e=>setStake(Math.max(.5,Number(e.target.value)||.5))} disabled={running}/></label><label><span className="ia-label">META MT</span><input className="ia-input" type="number" value={target} onChange={e=>setTarget(Math.max(1,Number(e.target.value)||1))}/></label></div>
 <div className="ia-card ia-grid"><div className="ia-box"><span className="ia-label">PRÓXIMA ENTRADA</span><b className="ia-value">${nextStake.toFixed(2)}</b></div><div className="ia-box"><span className="ia-label">SOROS</span><b className="ia-value">{soros}/3</b></div></div>
 <div className="ia-card"><div className="ia-label">SINAL</div><div className="ia-signal">{direction?direction==='EVEN'?'PAR':'ÍMPAR':'Aguardando 2 dígitos iguais'}</div><div className="ia-digits">{digits.map((d,i)=><div className="ia-digit" key={`${d}-${i}`}>{d}</div>)}</div></div>
 <button className={`ia-btn ${running?'stop':''}`} onClick={running?()=>setRunning(false):start} disabled={!isConnected||!isAuthorized}>{running?'■ PARAR IA Hper1':'▶ INICIAR IA Hper1'}</button>
 <div className="ia-card"><div className="ia-label">HISTÓRICO</div><div className="ia-history">{profitTransactions.slice(0,8).map(x=><div className="ia-row" key={x.contract_id}><span>{x.contract_type}</span><b className={Number(x.profit_loss)>=0?'ia-pos':'ia-neg'}>{Number(x.profit_loss)>=0?'+':''}{(Number(x.profit_loss)*USD_MZN).toFixed(0)} MT</b></div>)}</div></div>
 </div>;
}
