'use client';

import { useEffect, useState, useRef, useCallback } from 'react';
import { DerivWebSocket } from '@/lib/websocket';

interface Balance { balance:number; currency:string; loginid?:string }
interface Tick { symbol:string; quote:number; epoch:number }
interface Transaction { id:number; action:string; amount:number; currency:string; contract_id?:number }
interface ProfitTransaction { contract_id:number; buy_price:number; sell_price:number|null; payout:number; purchase_time:number; sell_time:number|null; contract_type:string; longcode?:string; profit_loss?:number; exit_tick?:number|string|null; exit_spot?:number|string|null }
interface Proposal { id:string; ask_price:number; payout:number; stake:number; contract_type:string; symbol:string; duration:number; duration_unit:string; barrier?:number }

const SOROS_MIN = 1.50;
const SOROS_MAX_WINS = 3;
const SOROS_STORAGE = 'mozhyper-soros-state-v7';
interface SorosState { level:number; stake:number; initialStake:number; accumulatedProfit:number; lossRetryCount:number; enabled:boolean; blocked:boolean }
const defaultSoros=(initialStake=SOROS_MIN):SorosState=>({level:0,stake:Math.max(SOROS_MIN,initialStake),initialStake:Math.max(SOROS_MIN,initialStake),accumulatedProfit:0,lossRetryCount:0,enabled:true,blocked:false});

// Soros is intentionally session-only. A page refresh starts a completely new Soros cycle.
function loadSoros():SorosState{return defaultSoros()}
function saveSoros(s:SorosState){if(typeof window==='undefined')return;try{sessionStorage.setItem(SOROS_STORAGE,JSON.stringify(s))}catch{}}
function clearSorosStorage(){if(typeof window==='undefined')return;try{sessionStorage.removeItem(SOROS_STORAGE);sessionStorage.removeItem('mozhyper-soros-state-v6')}catch{}}
function calculateProfitLoss(tx:Partial<ProfitTransaction>):number{const explicit=Number(tx.profit_loss);if(Number.isFinite(explicit)&&Math.abs(explicit)>0.000001)return explicit;const buy=Number(tx.buy_price),sell=Number(tx.sell_price);if(Number.isFinite(buy)&&Number.isFinite(sell))return sell-buy;return Number.isFinite(explicit)?explicit:0}

export function useDeriv(accountType:'demo'|'real'='demo'){
 const wsRef=useRef<DerivWebSocket|null>(null),activeContractRef=useRef<number|null>(null),latestProposalReqRef=useRef<number|null>(null),closedContractsRef=useRef<Map<number,ProfitTransaction>>(new Map()),sessionStartedAtRef=useRef(Math.floor(Date.now()/1000)),sorosRef=useRef<SorosState>(defaultSoros()),lastProcessedSorosContractRef=useRef<number|null>(null);
 const[balance,setBalance]=useState<Balance|null>(null),[tick,setTick]=useState<Tick|null>(null),[transaction,setTransaction]=useState<Transaction|null>(null),[isConnected,setIsConnected]=useState(false),[isAuthorized,setIsAuthorized]=useState(false),[error,setError]=useState<string|null>(null),[profitTransactions,setProfitTransactions]=useState<ProfitTransaction[]>([]),[profitCount,setProfitCount]=useState(0),[proposal,setProposal]=useState<Proposal|null>(null),[loadingProfit,setLoadingProfit]=useState(false),[buying,setBuying]=useState(false),[contractClosedSeq,setContractClosedSeq]=useState(0),[activeContractId,setActiveContractId]=useState<number|null>(null),[soros,setSoros]=useState<SorosState>(()=>defaultSoros());
 const syncSoros=useCallback((next:SorosState)=>{const initial=Math.max(SOROS_MIN,Number(next.initialStake)||SOROS_MIN);const accumulated=Math.max(0,Number(next.accumulatedProfit)||0);const normalized={...next,initialStake:initial,stake:accumulated>0?Math.max(0.01,Number(next.stake)||accumulated):initial,accumulatedProfit:accumulated,lossRetryCount:0,level:Math.max(0,Math.floor(Number(next.level)||0)),enabled:true,blocked:false};sorosRef.current=normalized;setSoros(normalized);saveSoros(normalized)},[]);
 const resetSoros=useCallback((initialStake=sorosRef.current.initialStake)=>syncSoros(defaultSoros(initialStake)),[syncSoros]);
 const setSorosEnabled=useCallback((_enabled:boolean)=>syncSoros({...sorosRef.current,enabled:true}),[syncSoros]);
 const setSorosStake=useCallback((initialStake:number)=>{const value=Math.max(SOROS_MIN,Number(initialStake)||SOROS_MIN);const s=sorosRef.current;if(s.level===0&&s.accumulatedProfit===0)syncSoros({...s,stake:value,initialStake:value,enabled:true,blocked:false})},[syncSoros]);
 const processSorosResult=useCallback((tx:ProfitTransaction)=>{if(lastProcessedSorosContractRef.current===tx.contract_id)return;const pnl=calculateProfitLoss(tx);if(!Number.isFinite(pnl)||Math.abs(pnl)<0.000001)return;lastProcessedSorosContractRef.current=tx.contract_id;const s=sorosRef.current;
   if(pnl>0){const accumulated=Math.max(0,s.accumulatedProfit+pnl);const nextLevel=s.level+1;if(nextLevel>=SOROS_MAX_WINS){syncSoros(defaultSoros(s.initialStake));return;}syncSoros({level:nextLevel,stake:accumulated,initialStake:s.initialStake,accumulatedProfit:accumulated,lossRetryCount:0,enabled:true,blocked:false});return;}
   syncSoros(defaultSoros(s.initialStake));
 },[syncSoros]);
 const mergeProfitTransactions=useCallback((incoming:ProfitTransaction[])=>{for(const tx of incoming){const id=Number(tx.contract_id),purchaseTime=Number(tx.purchase_time??0);if(!Number.isFinite(id)||id<=0||!purchaseTime||purchaseTime<sessionStartedAtRef.current)continue;const previous=closedContractsRef.current.get(id);const raw:any={...previous,...tx};const normalized:ProfitTransaction={contract_id:id,buy_price:Number(raw.buy_price??0),sell_price:raw.sell_price==null?null:Number(raw.sell_price),payout:Number(raw.payout??0),purchase_time:Number(raw.purchase_time??purchaseTime),sell_time:raw.sell_time==null?null:Number(raw.sell_time),contract_type:String(raw.contract_type??''),longcode:raw.longcode,profit_loss:calculateProfitLoss(raw),exit_tick:raw.exit_tick??null,exit_spot:raw.exit_spot??null};closedContractsRef.current.set(id,normalized);if(normalized.sell_time&&normalized.sell_time>0)processSorosResult(normalized)}const merged=Array.from(closedContractsRef.current.values()).sort((a,b)=>Number(b.sell_time??b.purchase_time)-Number(a.sell_time??a.purchase_time)).slice(0,50);setProfitTransactions(merged);setProfitCount(merged.length)},[processSorosResult]);
 const refreshProfitTable=useCallback(()=>wsRef.current?.getProfitTable({limit:50,offset:0,sort:'DESC',description:1}),[]);
 useEffect(()=>{let cancelled=false;let connectionCheck:ReturnType<typeof setInterval>|null=null;let initialProfitLoaded=false;let lastProfitRefresh=0;sessionStartedAtRef.current=Math.floor(Date.now()/1000);closedContractsRef.current.clear();setProfitTransactions([]);setProfitCount(0);setBalance(null);setProposal(null);setError(null);setBuying(false);setContractClosedSeq(0);setActiveContractId(null);clearSorosStorage();sorosRef.current=defaultSoros();setSoros(sorosRef.current);lastProcessedSorosContractRef.current=null;
   const refresh=(force=false)=>{const now=Date.now();if(!force&&now-lastProfitRefresh<1500)return;lastProfitRefresh=now;setLoadingProfit(true);refreshProfitTable()};
   const start=async()=>{try{const response=await fetch(`/api/deriv/ws-url?account_type=${accountType}`,{cache:'no-store',credentials:'same-origin'});const session=await response.json().catch(()=>null);if(!response.ok||!session?.wsUrl)throw new Error(session?.error||`Unable to create Deriv WebSocket session (${response.status})`);if(cancelled)return;const ws=new DerivWebSocket(session.wsUrl);wsRef.current=ws;
     ws.subscribe('*',(data)=>{if(!data.error)return;const message=data.error.message||'Unknown Deriv error';if(data.echo_req?.forget!==undefined)return;if(data.error.code==='RateLimit'||/rate.?limit/i.test(message)){setLoadingProfit(false);return}if(/unknown contract/i.test(message)&&(data.echo_req?.profit_table||data.echo_req?.proposal_open_contract)){setLoadingProfit(false);return}if(data.echo_req?.buy){setBuying(false);setProposal(null);activeContractRef.current=null;setActiveContractId(null);latestProposalReqRef.current=null}if(data.echo_req?.proposal){setBuying(false);setProposal(null);latestProposalReqRef.current=null}setError(message);if(data.error.code==='AuthorizationRequired'||data.error.code==='Unauthorized')setIsAuthorized(false)});
     ws.subscribe('authorize',data=>{if(data.authorize)setIsAuthorized(true)});ws.subscribe('balance',data=>{if(data.balance)setBalance(data.balance)});ws.subscribe('tick',data=>{if(data.tick)setTick(data.tick)});ws.subscribe('transaction',data=>{if(data.transaction)setTransaction(data.transaction)});ws.subscribe('profit_table',data=>{if(data.profit_table){mergeProfitTransactions(data.profit_table.transactions||[]);setLoadingProfit(false)}});
     ws.subscribe('proposal_open_contract',data=>{const c=data.proposal_open_contract;if(!c)return;const contractId=Number(c.contract_id);if(!Number.isFinite(contractId)||contractId<=0||activeContractRef.current!==contractId)return;const buyPrice=Number(c.buy_price??0),sellPrice=c.sell_price==null?null:Number(c.sell_price),payout=Number(c.payout??0),profitLoss=calculateProfitLoss({buy_price:buyPrice,sell_price:sellPrice,profit_loss:c.profit_loss}),purchaseTime=Number(c.purchase_time||Math.floor(Date.now()/1000)),sellTime=c.sell_time?Number(c.sell_time):null;if(c.is_sold||c.status==='won'||c.status==='lost'){const closedTx:ProfitTransaction={contract_id:contractId,buy_price:buyPrice,sell_price:sellPrice,payout,purchase_time:purchaseTime,sell_time:sellTime,contract_type:c.contract_type||'',longcode:c.longcode,profit_loss:profitLoss,exit_tick:c.exit_tick??null,exit_spot:c.exit_spot??null};processSorosResult(closedTx);mergeProfitTransactions([closedTx]);setLoadingProfit(false);activeContractRef.current=null;setActiveContractId(null);latestProposalReqRef.current=null;setProposal(null);setBuying(false);setContractClosedSeq(v=>v+1);ws.unsubscribeContract(contractId);window.setTimeout(()=>{if(!cancelled)refresh()},500)}});
     ws.subscribe('proposal',data=>{if(!data.proposal||activeContractRef.current!==null)return;const responseReqId=Number(data.req_id??data.echo_req?.req_id);if(latestProposalReqRef.current!==null&&responseReqId!==latestProposalReqRef.current)return;setProposal({id:data.proposal.id,ask_price:Number(data.proposal.ask_price),payout:Number(data.proposal.payout),stake:Number(data.proposal.stake),contract_type:data.proposal.contract_type,symbol:data.proposal.symbol||data.proposal.underlying_symbol,duration:Number(data.proposal.duration),duration_unit:data.proposal.duration_unit,barrier:data.proposal.barrier});setError(null)});
     ws.subscribe('buy',data=>{if(!data.buy)return;setBuying(false);const contractId=Number(data.buy.contract_id);if(Number.isFinite(contractId)&&contractId>0){activeContractRef.current=contractId;setActiveContractId(contractId);latestProposalReqRef.current=null;setProposal(null);ws.subscribeContract(contractId)}});ws.connect();
     connectionCheck=setInterval(()=>{if(cancelled)return;const connected=ws.isConnected();setIsConnected(connected);if(connected){setIsAuthorized(true);setError(prev=>prev==='Not authorized'?null:prev);ws.subscribeBalance();if(!initialProfitLoaded){initialProfitLoaded=true;refresh(true)}if(connectionCheck){clearInterval(connectionCheck);connectionCheck=null}}else setIsAuthorized(false)},250);
   }catch(err){if(!cancelled){setIsConnected(false);setIsAuthorized(false);setError(err instanceof Error?err.message:'Unable to initialize Deriv connection')}}};start();return()=>{cancelled=true;if(connectionCheck)clearInterval(connectionCheck);wsRef.current?.disconnect();wsRef.current=null;activeContractRef.current=null;latestProposalReqRef.current=null;closedContractsRef.current.clear();setActiveContractId(null)}},[accountType,refreshProfitTable,mergeProfitTransactions,processSorosResult]);
 const subscribeTicks=useCallback((symbol:string)=>wsRef.current?.subscribeTicks(symbol),[]);const fetchProfitTable=useCallback((options?:{limit?:number;offset?:number;sort?:'ASC'|'DESC'})=>{setLoadingProfit(true);wsRef.current?.getProfitTable({description:1,...options})},[]);
 const getProposal=useCallback((symbol:string,contractType:string,amount:number,duration:number,barrier=0)=>{if(activeContractRef.current!==null)return false;const s=sorosRef.current;const fallback=Math.max(SOROS_MIN,Number(amount)||SOROS_MIN);const effectiveAmount=s.accumulatedProfit>0?Math.max(0.01,s.stake):Math.max(SOROS_MIN,Number(s.initialStake)||fallback);if(s.level===0&&s.accumulatedProfit===0&&Math.abs(s.initialStake-effectiveAmount)>0.000001){const next={...s,stake:effectiveAmount,initialStake:effectiveAmount};sorosRef.current=next;setSoros(next);saveSoros(next)}setProposal(null);setError(null);const reqId=wsRef.current?.getProposal(symbol,contractType,effectiveAmount,duration,barrier);if(typeof reqId==='number')latestProposalReqRef.current=reqId;return typeof reqId==='number'},[]);
 const buy=useCallback((proposalId:string,price:number)=>{if(!proposalId||buying||activeContractRef.current!==null)return false;setBuying(true);const sent=wsRef.current?.buyContract(proposalId,price);if(!sent){setBuying(false);setProposal(null);setError('Não foi possível enviar a compra à Deriv.')}return!!sent},[buying]);
 const sell=useCallback((contractId:number)=>wsRef.current?.sellContract(contractId),[]);
 return{balance,tick,transaction,isConnected,isAuthorized,error,profitTransactions,profitCount,proposal,loadingProfit,buying,activeContractId,contractClosedSeq,subscribeTicks,fetchProfitTable,getProposal,buy,sell,soros,resetSoros,setSorosEnabled,setSorosStake};
}